from __future__ import annotations

import csv
import hashlib
import io
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Iterable
from urllib.parse import urlparse

from backend.rights_engine import evaluate_rights, rights_metadata_for_book


SOURCE_INGESTION_FIELDS = [
    "source_url",
    "source_name",
    "source_license",
    "source_hash",
    "raw_text",
    "cleaned_text",
    "language",
    "chapter_segments",
    "ingestion_status",
    "ingestion_log",
]

ALLOWED_CONNECTORS = {
    "auto",
    "manual-url",
    "manual-text",
    "project-gutenberg",
    "wikisource",
    "scanned-pdf-placeholder",
}

UNSAFE_SOURCE_LICENSE_RE = re.compile(
    r"\b(all\s+rights\s+reserved|non[-\s]?commercial|cc[-\s]?by[-\s]?nc|unknown|unclear|restricted)\b",
    re.IGNORECASE,
)

GUTENBERG_START_RE = re.compile(r"\*\*\*\s*START OF (?:THE|THIS) PROJECT GUTENBERG EBOOK.*?\*\*\*", re.IGNORECASE)
GUTENBERG_END_RE = re.compile(r"\*\*\*\s*END OF (?:THE|THIS) PROJECT GUTENBERG EBOOK.*?\*\*\*", re.IGNORECASE)
HEADER_FOOTER_LINE_RE = re.compile(
    r"^\s*(?:page\s+\d+|\d+\s*|project gutenberg|produced by|generated by|transcribed by)\s*$",
    re.IGNORECASE,
)
CHAPTER_HEADING_RE = re.compile(
    r"^(chapter\s+(?:[ivxlcdm]+|\d+|one|two|three|four|five|six|seven|eight|nine|ten)\b|"
    r"book\s+\d+\b|part\s+\d+\b|"
    r"\u0985\u09a7\u09cd\u09af\u09be\u09af\u09bc\b|"
    r"\u09aa\u09b0\u09bf\u099a\u09cd\u099b\u09c7\u09a6\b)",
    re.IGNORECASE,
)


@dataclass
class ChapterSegment:
    title: str
    order: int
    content: str

    def as_dict(self) -> dict[str, Any]:
        return {
            "title": self.title,
            "order": self.order,
            "content": self.content,
            "character_count": len(self.content),
            "word_count": len(self.content.split()),
        }


@dataclass
class SourceIngestionRecord:
    source_url: str
    source_name: str
    source_license: str
    source_hash: str
    raw_text: str
    cleaned_text: str
    language: str
    chapter_segments: list[dict[str, Any]] = field(default_factory=list)
    ingestion_status: str = "READY"
    ingestion_log: list[str] = field(default_factory=list)
    connector: str = "manual-text"
    rights_status: str = ""
    downstream_artifacts_regenerated: bool = False
    dry_run: bool = True
    generated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def as_dict(self, *, include_text: bool = True) -> dict[str, Any]:
        row = {
            "source_url": self.source_url,
            "source_name": self.source_name,
            "source_license": self.source_license,
            "source_hash": self.source_hash,
            "raw_text": self.raw_text if include_text else "",
            "cleaned_text": self.cleaned_text if include_text else "",
            "language": self.language,
            "chapter_segments": self.chapter_segments,
            "ingestion_status": self.ingestion_status,
            "ingestion_log": self.ingestion_log,
            "connector": self.connector,
            "rights_status": self.rights_status,
            "downstream_artifacts_regenerated": self.downstream_artifacts_regenerated,
            "dry_run": self.dry_run,
            "generated_at": self.generated_at,
        }
        return row


@dataclass
class SourceIngestionInput:
    book: dict[str, Any]
    raw_text: str = ""
    source_url: str = ""
    source_name: str = ""
    source_license: str = ""
    language: str = ""
    connector: str = "auto"
    previous_source_hashes: set[str] = field(default_factory=set)
    dry_run: bool = True


def ingest_source(payload: SourceIngestionInput) -> SourceIngestionRecord:
    source_url, source_name, source_license = source_metadata(payload)
    connector = normalize_connector(payload.connector, source_url, payload.raw_text)
    rights_status, blockers = ingestion_rights_blockers(
        payload.book,
        source_url=source_url,
        source_name=source_name,
        source_license=source_license,
    )
    ingestion_log = [f"connector={connector}", f"rights_status={rights_status}"]

    if connector == "scanned-pdf-placeholder":
        source_hash = hash_source(payload.raw_text or source_url)
        ingestion_log.append("Scanned PDF ingestion is a placeholder until OCR is implemented.")
        return SourceIngestionRecord(
            source_url=source_url,
            source_name=source_name,
            source_license=source_license,
            source_hash=source_hash,
            raw_text=payload.raw_text,
            cleaned_text="",
            language=payload.language or "unknown",
            ingestion_status="PENDING_OCR",
            ingestion_log=ingestion_log,
            connector=connector,
            rights_status=rights_status,
            downstream_artifacts_regenerated=False,
            dry_run=payload.dry_run,
        )

    if blockers:
        source_hash = hash_source(payload.raw_text)
        return SourceIngestionRecord(
            source_url=source_url,
            source_name=source_name,
            source_license=source_license,
            source_hash=source_hash,
            raw_text=payload.raw_text,
            cleaned_text="",
            language=payload.language or "unknown",
            ingestion_status="BLOCKED_RIGHTS",
            ingestion_log=[*ingestion_log, *blockers],
            connector=connector,
            rights_status=rights_status,
            downstream_artifacts_regenerated=False,
            dry_run=payload.dry_run,
        )

    if not payload.raw_text.strip():
        return SourceIngestionRecord(
            source_url=source_url,
            source_name=source_name,
            source_license=source_license,
            source_hash=hash_source(""),
            raw_text="",
            cleaned_text="",
            language=payload.language or "unknown",
            ingestion_status="BLOCKED_EMPTY_SOURCE",
            ingestion_log=[*ingestion_log, "raw_text is required for text ingestion."],
            connector=connector,
            rights_status=rights_status,
            downstream_artifacts_regenerated=False,
            dry_run=payload.dry_run,
        )

    source_hash = hash_source(payload.raw_text)
    cleaned_text = clean_source_text(payload.raw_text, connector=connector)
    language = payload.language or detect_language(cleaned_text)
    segments = [segment.as_dict() for segment in detect_chapters(cleaned_text)]
    unchanged = source_hash in payload.previous_source_hashes
    ingestion_status = "UNCHANGED" if unchanged else "READY"
    downstream_artifacts_regenerated = not unchanged
    if unchanged:
        ingestion_log.append("source_hash matches an existing source; downstream regeneration skipped.")
    else:
        ingestion_log.append("source_hash is new; downstream artifacts may be regenerated after review.")

    return SourceIngestionRecord(
        source_url=source_url,
        source_name=source_name,
        source_license=source_license,
        source_hash=source_hash,
        raw_text=payload.raw_text,
        cleaned_text=cleaned_text,
        language=language,
        chapter_segments=segments,
        ingestion_status=ingestion_status,
        ingestion_log=ingestion_log,
        connector=connector,
        rights_status=rights_status,
        downstream_artifacts_regenerated=downstream_artifacts_regenerated,
        dry_run=payload.dry_run,
    )


def ingestion_rights_blockers(
    book: dict[str, Any],
    *,
    source_url: str = "",
    source_name: str = "",
    source_license: str = "",
) -> tuple[str, list[str]]:
    metadata = rights_metadata_for_book(book)
    if source_url:
        metadata["source_url"] = source_url
    if source_name:
        metadata["source_name"] = source_name
    if source_license:
        metadata["source_license"] = source_license
    candidate = {**book, "rights_metadata": metadata}

    blockers: list[str] = []
    for field_name in ("source_url", "source_name", "source_license"):
        if not str(metadata.get(field_name) or "").strip():
            blockers.append(f"{field_name} is required before source ingestion.")

    if metadata.get("source_license") and UNSAFE_SOURCE_LICENSE_RE.search(str(metadata["source_license"])):
        blockers.append("source_license is restricted, unclear, or unsafe for ingestion.")

    if str(metadata.get("blocked_reason") or "").strip():
        blockers.append("blocked_reason must be cleared before source ingestion.")

    rights_tier = str(metadata.get("rights_tier") or "").upper().replace("TIER ", "")
    if rights_tier not in {"A", "B"}:
        blockers.append("rights_tier must be A or B for source ingestion.")

    decision = evaluate_rights(candidate)
    if decision.approved:
        return "RIGHTS_APPROVED", blockers

    allowed_pending_issues = {
        "verification_status must be approved before publishing.",
    }
    disallowed = [issue for issue in decision.issues if issue not in allowed_pending_issues]
    if not blockers and not disallowed:
        return "RIGHTS_PENDING_SAFE", []

    return "RIGHTS_BLOCKED", [*blockers, *disallowed]


def source_metadata(payload: SourceIngestionInput) -> tuple[str, str, str]:
    metadata = rights_metadata_for_book(payload.book)
    source_url = payload.source_url or str(metadata.get("source_url") or "")
    source_name = payload.source_name or str(metadata.get("source_name") or "")
    source_license = payload.source_license or str(metadata.get("source_license") or "")
    return source_url.strip(), source_name.strip(), source_license.strip()


def normalize_connector(connector: str, source_url: str, raw_text: str) -> str:
    connector = (connector or "auto").strip().lower()
    if connector not in ALLOWED_CONNECTORS:
        raise ValueError(f"Unsupported connector: {connector}")
    if connector != "auto":
        return connector
    host = urlparse(source_url or "").netloc.lower()
    path = urlparse(source_url or "").path.lower()
    if "gutenberg.org" in host:
        return "project-gutenberg"
    if "wikisource.org" in host:
        return "wikisource"
    if path.endswith(".pdf"):
        return "scanned-pdf-placeholder"
    if raw_text:
        return "manual-text"
    return "manual-url"


def hash_source(raw_text: str) -> str:
    normalized = raw_text.replace("\r\n", "\n").replace("\r", "\n")
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def clean_source_text(raw_text: str, *, connector: str = "manual-text") -> str:
    text = raw_text.replace("\r\n", "\n").replace("\r", "\n")
    if connector == "project-gutenberg":
        text = strip_gutenberg_boilerplate(text)
    lines = []
    for line in text.splitlines():
        normalized = re.sub(r"\s+", " ", line).strip()
        if not normalized:
            lines.append("")
            continue
        if HEADER_FOOTER_LINE_RE.match(normalized):
            continue
        lines.append(normalized)
    text = "\n".join(lines)
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = re.sub(r"[ \t]+", " ", text)
    return text.strip()


def strip_gutenberg_boilerplate(text: str) -> str:
    start_match = GUTENBERG_START_RE.search(text)
    if start_match:
        text = text[start_match.end() :]
    end_match = GUTENBERG_END_RE.search(text)
    if end_match:
        text = text[: end_match.start()]
    return text


def detect_language(text: str) -> str:
    if not text.strip():
        return "unknown"
    bengali = len(re.findall(r"[\u0980-\u09ff]", text))
    latin = len(re.findall(r"[A-Za-z]", text))
    total = max(1, bengali + latin)
    if bengali / total >= 0.25:
        return "ben"
    if latin / total >= 0.60:
        return "en"
    return "unknown"


def detect_chapters(cleaned_text: str) -> list[ChapterSegment]:
    lines = cleaned_text.splitlines()
    headings: list[tuple[int, str]] = []
    for index, line in enumerate(lines):
        candidate = line.strip()
        if 0 < len(candidate) <= 120 and CHAPTER_HEADING_RE.match(candidate):
            headings.append((index, candidate))

    if not headings:
        return [ChapterSegment(title="Full Text", order=1, content=cleaned_text)] if cleaned_text else []

    segments: list[ChapterSegment] = []
    for order, (line_index, title) in enumerate(headings, start=1):
        next_line_index = headings[order][0] if order < len(headings) else len(lines)
        body = "\n".join(lines[line_index + 1 : next_line_index]).strip()
        segments.append(ChapterSegment(title=title, order=order, content=body))
    return segments


def ingestion_report_csv(records: Iterable[SourceIngestionRecord]) -> str:
    fieldnames = [
        "source_url",
        "source_name",
        "source_license",
        "source_hash",
        "language",
        "connector",
        "rights_status",
        "ingestion_status",
        "chapter_count",
        "raw_character_count",
        "cleaned_character_count",
        "downstream_artifacts_regenerated",
        "dry_run",
        "ingestion_log",
    ]
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=fieldnames, extrasaction="ignore")
    writer.writeheader()
    for record in records:
        writer.writerow({
            "source_url": record.source_url,
            "source_name": record.source_name,
            "source_license": record.source_license,
            "source_hash": record.source_hash,
            "language": record.language,
            "connector": record.connector,
            "rights_status": record.rights_status,
            "ingestion_status": record.ingestion_status,
            "chapter_count": len(record.chapter_segments),
            "raw_character_count": len(record.raw_text),
            "cleaned_character_count": len(record.cleaned_text),
            "downstream_artifacts_regenerated": record.downstream_artifacts_regenerated,
            "dry_run": record.dry_run,
            "ingestion_log": " | ".join(record.ingestion_log),
        })
    return output.getvalue()


def ingestion_report_markdown(records: list[SourceIngestionRecord]) -> str:
    lines = [
        "# Source Ingestion Dry-Run Report",
        "",
        "No production content was mutated. Source text and cleaned text are stored separately in this report.",
        "",
        "| Source | Connector | Rights | Status | Language | Chapters | Hash |",
        "| --- | --- | --- | --- | --- | ---: | --- |",
    ]
    for record in records:
        lines.append(
            "| "
            f"{record.source_name or record.source_url or 'local text'} | "
            f"{record.connector} | "
            f"{record.rights_status} | "
            f"{record.ingestion_status} | "
            f"{record.language} | "
            f"{len(record.chapter_segments)} | "
            f"{record.source_hash[:12]} |"
        )
    lines.extend([
        "",
        "## Guardrails",
        "",
        "- Missing source URL, source name, or source license blocks ingestion.",
        "- Rights Tier C and blocked rights records are blocked before cleanup or segmentation.",
        "- Unchanged source hashes skip downstream regeneration.",
        "- Scanned PDF ingestion is a placeholder until OCR is explicitly implemented.",
    ])
    return "\n".join(lines) + "\n"
