#!/usr/bin/env sh
set -eu

# Railway production web process: serve API traffic only. Expensive book/audio/
# cover/release jobs must use explicit manual commands and ENABLE_* flags.
export ENVIRONMENT="${ENVIRONMENT:-production}"
export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
export PYTHONDONTWRITEBYTECODE="${PYTHONDONTWRITEBYTECODE:-1}"
export MALLOC_ARENA_MAX="${MALLOC_ARENA_MAX:-2}"
export COST_CONTROL_MODE="${COST_CONTROL_MODE:-true}"
export ENABLE_BACKGROUND_WORKERS="${ENABLE_BACKGROUND_WORKERS:-false}"
export ENABLE_AUDIOBOOK_PIPELINE="${ENABLE_AUDIOBOOK_PIPELINE:-false}"
export ENABLE_BOOK_RENDERING_JOBS="${ENABLE_BOOK_RENDERING_JOBS:-false}"
export ENABLE_COVER_GENERATION="${ENABLE_COVER_GENERATION:-false}"
export ENABLE_SCHEDULED_JOBS="${ENABLE_SCHEDULED_JOBS:-false}"
export ENABLE_QUEUE_CONSUMER="${ENABLE_QUEUE_CONSUMER:-false}"
export ENABLE_ADMIN_MEDIA_UPLOADS="${ENABLE_ADMIN_MEDIA_UPLOADS:-false}"
export ENABLE_STARTUP_DB_MAINTENANCE="${ENABLE_STARTUP_DB_MAINTENANCE:-false}"
export MAX_CONCURRENT_JOBS="${MAX_CONCURRENT_JOBS:-1}"
export MONGODB_MAX_POOL_SIZE="${MONGODB_MAX_POOL_SIZE:-8}"
export PUBLIC_CACHE_MAX_ENTRIES="${PUBLIC_CACHE_MAX_ENTRIES:-96}"
export HOME_BOOK_LIMIT="${HOME_BOOK_LIMIT:-120}"
export REQUEST_BODY_LIMIT_BYTES="${REQUEST_BODY_LIMIT_BYTES:-2097152}"
export DOCX_UPLOAD_MAX_BYTES="${DOCX_UPLOAD_MAX_BYTES:-8388608}"
export CHAPTER_UPLOAD_MAX_BYTES="${CHAPTER_UPLOAD_MAX_BYTES:-8388608}"
export ADMIN_MEDIA_UPLOAD_MAX_BYTES="${ADMIN_MEDIA_UPLOAD_MAX_BYTES:-4194304}"

exec uvicorn server:app \
  --host 0.0.0.0 \
  --port "${PORT:-8000}" \
  --workers "${WEB_CONCURRENCY:-1}" \
  --proxy-headers \
  --forwarded-allow-ips '*' \
  --timeout-keep-alive "${UVICORN_KEEP_ALIVE:-10}" \
  --timeout-graceful-shutdown "${UVICORN_GRACEFUL_TIMEOUT:-10}"
