from pathlib import Path
from datetime import datetime,timezone
from collections import Counter
import json,hashlib,shutil
R=Path('/tmp/earnalism-main-approved-integration');S=Path('/workspace/scratch/181ef0a25f05');L=R/'internal/earnalism_intelligence/book_go_live_477_continuation_20261002/owner-delegated-completion-20261003/next-cohort';read=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
prior=S/'final-sprint-dispositions-20261003-v2/final-sprint-dispositions.json';pold=read(prior);shutil.copyfile(prior,L/'prior-immutable-dispositions-v2.json');release=read(R/'data/controlled_launch.json')['live_approved_slugs'];integration=read(L/'serialized-integration-receipt.json');oldset=set(integration['preserved_prior_released']);newset=set(integration['new_exact_slugs']);assert len(oldset)==33and len(newset)==19
rows=[]
for old in pold['entries']:
 slug=old['slug'];row={'slug':slug,'title':old['title'],'language':old['language'],'language_normalized':old['language_normalized'],'prior_assessment_preserved':old,'records_sources_artwork_decisions_versions_preserved':True,'production_canonical_version_observed':None}
 if slug in oldset:
  row.update(disposition='RELEASED_CONFIGURED_RETAIN_EXISTING_CANONICAL_EDITION',reason='Retained exact released edition; PR510 four additions completed protected merge and exact-main frontend/backend deployment/canary, with documented conditional India manual-observation waiver and truthful null canonical readback.',exact_blockers=[],terminal_exclusion_from_active_sprint=False,next_action='Preserve existing version/pointer and canonical edition; do not duplicate onboarding.')
 elif slug in newset:
  p=R/'data/controlled_publications'/slug;dec=read(p/'rights_decision.json');row.update(disposition='READY_BEHIND_PROTECTED_NORMAL_EXACT_HEAD_CI_MERGE_DEPLOY_CANARY_READBACK',reason='Actual prospective automated owner-delegated publication and exact owner-provided cover acceptance; two independent exact accepted-binding reviews PASS. Sole serialized integration complete; new cohort not deployed or observed yet.',exact_blockers=['PROTECTED_NORMAL_EXACT_HEAD_CI_MERGE_DEPLOY_CANARY_TRUTHFUL_READBACK'],terminal_exclusion_from_active_sprint=False,decision_id=dec['decision_id'],canonical_record_sha256=sha(p/'rights_decision.json'),next_action='Complete two independent current integrated-tree reviews and protected normal exact-head CI/merge/deployment/canary/readback; no unchanged preparation repetition.')
  from_sys_note='Canonical decision binding uses normalized canonical record SHA rather than raw JSON SHA.'
  import sys;sys.path.insert(0,str(R));from backend.rights_decision_gate import record_sha256;row['canonical_record_sha256']=record_sha256(dec)
  pub=read(p/'public_book.json');row['actual_current_delivery_urls']={'front':pub.get('cover_image_url')or pub.get('cover_url'),'back':pub.get('back_cover_image_url')or pub.get('back_cover_url')}
 else:row.update(disposition=old['disposition'],reason=old['reason'],exact_blockers=old.get('exact_blockers',[old['reason']]),terminal_exclusion_from_active_sprint=True,next_action='Dropped/held from this active sprint; preserve all records. Reconsider only on materially changed exact cleared evidence; no recurring retry, duplicate edition or unchanged investigation.')
 rows.append(row)
assert len(rows)==231 and len({r['slug']for r in rows})==231 and all(r['exact_blockers']or r['slug']in oldset for r in rows)
d={'schema':'earnalism.all-assessed-editions-disposition.immutable-candidate.v3','captured_at':datetime.now(timezone.utc).isoformat(),'prior_immutable_ledger_sha256':sha(prior),'assessed_editions':231,'all_assessed_editions_classified':True,'counts':dict(Counter(r['disposition']for r in rows)),'configured_count':52,'released_retained_count':33,'new_ready_count':19,'terminal_active_sprint_exclusions':179,'english':{'known_language_catalogue_records':124,'released_retained':28,'new_ready':15,'held_or_dropped':81,'entire_English_catalogue_live':False},'bengali':{'released_retained':5,'new_ready':4},'owner_artwork_provenance_basis':'Actual Ronik Basak creator/copyright-holder declaration SHA0881001b09b5b47649f14ff289aaa7f64e98004adc3d800f67d90fab703f9264, prospective only; prior methods/decisions preserved.','production_observed_for_new_cohort':False,'audio_exposed':False,'entire_catalogue_live':False,'safe_queue_exhaustion_claimed':False,'entries':rows,'next_action':'Finish sole existing integration through two exact-tree reviews, protected normal checks, merge/deploy/canary/truthful readback, then append final immutable disposition snapshot.'};write(L/'all-assessed-edition-dispositions-candidate.json',d)
sp=R/'internal/earnalism_intelligence/book_go_live_477_continuation_20261002/state.json';st=read(sp);write(L/'campaign-state-pre-next19.json',st);st.update(source_main='0fee65668f94284d180065d0fe8b38face924498',configured_candidate_count=52,continuation_status='NINETEEN_EXACT_ACCEPTED_EDITIONS_SERIALIZED_BEHIND_PROTECTED_RELEASE_GATE',next_action=d['next_action']);st['owner_provided_next19_integration']={'receipt_path':str((L/'serialized-integration-receipt.json').relative_to(R)),'new_exact_slugs':integration['new_exact_slugs'],'new_ready_count':19,'retained_released_count':33,'audio_exposed':False,'production_observed':False,'all_assessed_dispositions':str((L/'all-assessed-edition-dispositions-candidate.json').relative_to(R)),'terminal_active_sprint_exclusions':179,'original_cover_provenance_methods':'UNKNOWN facts preserved; current owner copyright/provenance declaration supplies actual new acceptance basis, not invented original method.'};write(sp,st);print(json.dumps({'classified':len(rows),'counts':d['counts'],'english':d['english']}))
