from pathlib import Path
import json,hashlib,sys
from datetime import datetime,timezone
P=Path('/workspace/scratch/181ef0a25f05');R=Path('/tmp/earnalism-main-approved-integration');B=Path(sys.argv[1]);O=P/'new-acceptance-review-a';sys.path.insert(0,str(R/'backend'));from publication_manifest import validate_manifest
from rights_decision_gate import evaluate_accepted_record,record_sha256
h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();rec=json.loads((B/'acceptance-receipt.json').read_text());rows=[]
for c in rec['cohort']:
 s=c['slug'];d=B/'data/controlled_publications'/s;dec=json.loads((d/'rights_decision.json').read_text());auth=json.loads((d/'publication_authorization.json').read_text());ap=json.loads((d/'approval_evidence.json').read_text());book=json.loads((d/'public_book.json').read_text());manifest=json.loads((d/'publication_manifest.json').read_text());cs=json.loads((d/'checksum_manifest.json').read_text())['files'];inv={str(f.relative_to(d)):h(f) for f in d.rglob('*') if f.is_file()};resolved={h(f):str(f.relative_to(B)) for f in d.rglob('*') if f.is_file()};resolved.update({h(B/a['path']):a['path'] for a in c['assets'].values()});assert all(v in resolved for v in dec['components'].values()),(s,[(k,v) for k,v in dec['components'].items() if v not in resolved]);assert all(h(d/x['file'])==x['sha256'] for x in cs);assert all(f.read_bytes()==(B/'backend'/f.relative_to(B)).read_bytes() for f in d.rglob('*') if f.is_file());assert record_sha256(dec)==c['canonical_record_sha256'];assert dec['status']=='ACCEPTED' and dec['conditions_satisfied'] and dec['territories']==['IN'];assert 'Automated' in dec['accepted_by'] and dec['valid_from']==rec['actual_acceptance_at'];assert auth['publication_authorized'] and not auth['audio_authorized'] and not auth['production_activation_authorized_by_this_file'];assert ap['approved_to_publish'] and not ap.get('audiobook_use_approved',False) and not ap.get('manual_listening_approval',False);assert not ap.get('production_observed',False);assert not validate_manifest(manifest),(s,validate_manifest(manifest));assert not manifest['audio_release']['exposed'];assert 'REQUIRED' in ap['binding_review_status'];assert all(h(d/x['file'])==x['sha256'] for x in c['reviews'].values())
 prior=(P/'classics6-prep-20261003'/s/'candidate-inactive-unaccepted') if s in ['the-time-machine','the-great-gatsby','frankenstein','the-secret-garden','pride-and-prejudice'] else (P/'practical-batch-prep-20261003'/s/'inactive-candidate') if s in ['the-principles-of-scientific-management','acres-of-diamonds','my-life-and-work'] else P/'bengali-next-cohort-20261003'/s/'proposal/data/controlled_publications'/s
 preserved=['source_evidence.json','highlight_sync.json']+[str(f.relative_to(d)) for f in (d/'chapters').glob('*.json')];assert all((d/n).read_bytes()==(prior/n).read_bytes() for n in preserved)
 for f in (d/'covers').glob('*'):assert f.read_bytes()==(prior/'covers'/f.name).read_bytes()
 proof={'accepted_record_integrity':True,'metadata_conditions_scope_actor':True,'source_chapter_sync_and_art_unchanged':True,'component_resolution':{k:resolved[v] for k,v in dec['components'].items()},'canonical_record_sha256':record_sha256(dec),'checksum_count':len(cs),'manifest_schema':True,'reviews_actual_bytes_bound':True,'gates':{}}
 for country,trusted,use in [('IN',True,u) for u in dec['uses']]+[('IN',True,'audio_stream'),('US',True,'reader_delivery'),('IN',False,'reader_delivery')]:
  v=evaluate_accepted_record(dec,edition_id=s,operator_id='reo-enterprise',country=country,country_trusted=trusted,use=use,required_components=dec['components'],accepted_records={dec['decision_id']:record_sha256(dec)},revoked_decision_ids=frozenset(),now=datetime.now(timezone.utc));expected=country=='IN' and trusted and use in dec['uses'];assert v.passed==expected,(s,use,country,v.reasons);proof['gates'][f'{country}/{trusted}/{use}']={'passed':v.passed,'reasons':list(v.reasons)}
 proof.update(slug=s,package_inventory=inv,audio_DISABLED=True,production_observed=False,canonical_mutations=0,hypothetical_exact_candidate_gate_only=True);rows.append(proof)
f=O/(B.name+'-binding-integrity-review-a-v1.json');assert not f.exists();f.write_text(json.dumps({'stage':str(B),'status':'INTEGRITY_PASS_COHERENCE_CHECK_SEPARATE','owner_basis_sha256':rec['owner_declaration_sha256'],'gate':rec['global_gate'],'titles':rows},ensure_ascii=False,indent=2)+'\n');print(str(f),h(f))
