from pathlib import Path
import json,hashlib,io,ast,unicodedata
from PIL import Image,ImageDraw,ImageFont,ImageChops
P=Path('/workspace/scratch/181ef0a25f05');R=Path('/tmp/earnalism-main-approved-integration');C=P/'classics6-prep-20261003';h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();norm=lambda t:' '.join(unicodedata.normalize('NFC',t).split());rows=[]
mod=ast.parse((C/'prepare_batch.py').read_text());fn=next(x for x in mod.body if isinstance(x,ast.FunctionDef) and x.name=='licensed_overlay');ns={'ImageDraw':ImageDraw,'ImageFont':ImageFont,'ImageChops':ImageChops,'FONT':R/'frontend/public/assets/fonts/eb-garamond-400.ttf','MASKBOTTOM':{'the-time-machine':420,'the-great-gatsby':450,'frankenstein':420,'the-secret-garden':560,'pride-and-prejudice':540,'great-expectations':580},'PALETTE':{'the-time-machine':'#14222b','the-great-gatsby':'#121e2b','frankenstein':'#1c242b','the-secret-garden':'#14251b','pride-and-prejudice':'#ead3aa','great-expectations':'#1e272c'}};exec(compile(ast.Module(body=[fn],type_ignores=[]),'isolated-function','exec'),ns)
for b in json.loads((C/'batch-result.json').read_text()):
 s=b['slug'];d=C/s/'candidate-inactive-unaccepted';cp=json.loads((d/'cover_preparation.json').read_text());book=json.loads((d/'public_book.json').read_text());dec=json.loads((d/'rights_decision.json').read_text());boundary=cp['boundary_receipt'];row={'slug':s,'checks':{},'assets':[]};check=row['checks']
 cs=json.loads((d/'checksum_manifest.json').read_text())['files'];check['all_checksums']=all(h(d/x['file'])==x['sha256'] for x in cs);check['components']=all(h(d/(k+'.json'))==v for k,v in dec['components'].items());check['source_reader_highlight_unchanged']=all((d/n).read_bytes()==(C/s/'preimages/root'/n).read_bytes() for n in ['source_evidence.json','reader_manifest.json','highlight_sync.json']);chs=sorted((d/'chapters').glob('*.json'));check['all_chapter_bytes_unchanged']=all(f.read_bytes()==(C/s/'preimages/root/chapters'/f.name).read_bytes() for f in chs);check['all_chapter_content_hashes']=all(hashlib.sha256(json.loads(f.read_text())['content'].encode()).hexdigest()==boundary['ordered_chapter_hashes'][json.loads(f.read_text())['id']] for f in chs);check['font_and_license_exact']=all(h(R/cp['title_author_gate'][k])==cp['title_author_gate'][k.replace('_file','_sha256')] for k in ['font_file','font_license_file']);check['owner_fact_exact']=h(Path(cp['owner_design_fact']['source']))==cp['owner_design_fact']['sha256'];check['inactive_unaccepted']=dec['status']=='PROPOSED' and not dec['conditions_satisfied'] and not book['isLive'] and not book['isPublic'];check['recipe_source_sha']=h(C/'prepare_batch.py')
 for a in b['assets']:
  original=Image.open(d/a['source_file']).convert('RGB');overlay=Image.open(d/a['licensed_deterministic_overlay']['file']).convert('RGB');rebuilt,mask=ns['licensed_overlay'](original,s,a['kind'],book['title'],book['author']);buf=io.BytesIO();rebuilt.save(buf,'PNG',compress_level=9);pngexact=hashlib.sha256(buf.getvalue()).hexdigest()==a['licensed_deterministic_overlay']['sha256'];diff=ImageChops.difference(original,overlay);m=Image.new('L',original.size,0);ImageDraw.Draw(m).rectangle(mask,fill=255);outside=ImageChops.multiply(diff,Image.merge('RGB',(ImageChops.invert(m),)*3)).getbbox() is None
  rec=a['recipe'];bb=io.BytesIO();overlay.resize(tuple(rec['resize']),Image.Resampling.LANCZOS).save(bb,'WEBP',quality=rec['quality'],method=rec['method']);we=hashlib.sha256(bb.getvalue()).hexdigest()==a['sha256'];im=Image.open(d/a['file']);im.load();row['assets'].append({'kind':a['kind'],'original_sha256':h(d/a['source_file']),'prepared_png_sha256':h(d/a['licensed_deterministic_overlay']['file']),'delivery_sha256':h(d/a['file']),'png_recipe_exact':pngexact,'outside_mask_RGB_exact':outside,'webp_recipe_exact':we,'dimensions':list(im.size),'bytes':(d/a['file']).stat().st_size,'budget_pass':(d/a['file']).stat().st_size <= (80000 if a['kind']=='front' else 180000)})
 if s=='the-great-gatsby':
  raw=R/'content/books/the-great-gatsby/raw/pg64317.txt';txt=norm(raw.read_text());cursor=0;gaps=[];positions=[]
  for f in chs:
   c=json.loads(f.read_text());body=norm(c['content']);pos=txt.find(body,cursor);assert pos>=0;gaps.append(txt[cursor:pos] if cursor else txt[:pos]);positions.append([pos,len(body)]);cursor=pos+len(body)
  row['complete_source_independent']={'raw_sha256':h(raw),'expected_primary_exact':h(raw)==boundary['raw_source_sha256'],'ordered_bodies_all_match':True,'internal_gaps':gaps[1:],'receipt_gaps_exact':[norm(x['text']) for x in boundary['internal_gaps']]==[norm(x) for x in gaps[1:]],'prefix_suffix_review':'Prefix only PG title/TOC furniture; dedication+epigraph retained chapter000. After narrative closes only PG END/license; selected complete author edition narrative.','suffix':txt[cursor:cursor+120]}
 row['rights_decision_raw_sha256']=h(d/'rights_decision.json');row['package_inventory']={str(f.relative_to(d)):h(f) for f in sorted(d.rglob('*')) if f.is_file()};rows.append(row)
f=P/'new-acceptance-review-a/classics-integrity-a-v1.json';assert not f.exists();f.write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n');print(str(f),h(f));print([(r['slug'],r['checks'],[(a['kind'],a['png_recipe_exact'],a['webp_recipe_exact'],a['outside_mask_RGB_exact']) for a in r['assets']]) for r in rows])
