from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,shutil
from PIL import Image
from fontTools.ttLib import TTFont
R=Path('/tmp/earnalism-main-approved-integration');O=Path(__file__).parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
canon=lambda d:hashlib.sha256(json.dumps(d,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
read=lambda p:json.loads(p.read_text())
def put(p,d):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
STAMP=datetime.now(timezone.utc).isoformat();records=[]
for slug in ['lokrahasya','mrinalini','bn-066']:
 out=O/slug;S=out/'preimages/root';P=out/'proposal/data/controlled_publications'/slug;old=read(S/'rights_decision.json');source=read(S/'source_evidence.json');prep=read(out/'cover-preparation.json');shutil.copytree(S,P,dirs_exist_ok=True)
 archive=out/'archive-excluded-active-claims';archive.mkdir(exist_ok=True)
 removed=[]
 for f in P.glob('*audio*evidence*.json'):shutil.copy2(f,archive/f.name);removed.append({'file':f.name,'sha256':sha(f)});f.unlink()
 assets={}
 for kind,a in prep['assets'].items():
  paths=[Path(a['original']['path']),Path(a['prepared_png']['path']),Path(a['delivery']['path'])];(P/'covers').mkdir(exist_ok=True)
  for x in paths:shutil.copy2(x,P/'covers'/x.name)
  assert sha(paths[0])==a['original']['sha256'];assert sha(paths[1])==a['prepared_png']['sha256'];assert sha(paths[2])==a['delivery']['sha256']
  name=f"{slug}-{kind}-{sha(paths[2])[:8]}.webp";static=out/'proposal/frontend/public/assets/books'/slug/name;static.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(paths[2],static)
  assets[kind]={'original_file':'covers/'+paths[0].name,'original_sha256':sha(paths[0]),'original_url':a['original']['url'],'prepared_file':'covers/'+paths[1].name,'prepared_sha256':sha(paths[1]),'delivery_file':'covers/'+paths[2].name,'delivery_sha256':sha(paths[2]),'delivery_url':'https://theearnalism.com/assets/books/'+slug+'/'+name,'delivery_bytes':paths[2].stat().st_size,'delivery_dimensions':list(Image.open(paths[2]).size),'production_observed':False}
 font_evidence=[]
 for x in prep['fonts']:
  p=R/x['path'];names=[]
  for n in TTFont(p)['name'].names:
   if n.nameID in [0,14]:names.append({'name_id':n.nameID,'value':n.toUnicode()})
  assert any(n['name_id']==14 and n['value']=='https://openfontlicense.org' for n in names)
  font_evidence.append({'path':x['path'],'sha256':sha(p),'embedded_copyright_and_license_url':names,'required_codepoint_and_raqm_checks':'PASS','new_font_method_claim':'Exact repository font files only; no inferred third-party generation method.'})
 owner='internal/legal/bengali_text_preparation_20261002/evidence_matrix.json';assert 'Owner states all front and back covers are designed by the owner.' in (R/owner).read_text()
 decision_id=f'india-20261003-{slug}-exact-edition-text-cover-proposal'
 cover={'schema':'earnalism.cover-provenance.v1','slug':slug,'status':'PROPOSED_PENDING_TWO_EXACT_REVIEWS_NOT_ACCEPTED','owner_declaration':{'statement':'Owner states all front and back covers are designed by the owner.','path':owner,'sha256':sha(R/owner),'scope':'Original design declaration only; no generation method or additional author identity inferred.'},'prospective_owner_delegation':'User Oct3 explicit evidence-based cover/publication acceptance superseding prior procedural cover deferral in existing issue477 campaign; fresh evidence reviews remain required.','edition_binding':{'text_decision_id':old['decision_id'],'source_sha256':source['source_hash'],'content_sha256':source['content_hash'],'chapter_count':read(out/'source-validation.json')['chapter_count']},'assets':assets,'derivative_lineage':{'recovery_receipt_sha256':sha(out/'recovery-receipt.json'),'cover_preparation_sha256':sha(out/'cover-preparation.json'),'renderer_sha256':sha(O/'render.py'),'method':prep['method'],'original_illustration_outside_masks_pixel_identity':True,'one_bounded_combined_remediation_attempt':1,'metadata_binding':prep['metadata_binding'],'font_licenses':font_evidence},'independent_reviews':[],'commercial_use_authorized':False,'audio_authorized':False,'runtime_release_authorized':False,'production_observed':False}
 put(P/'cover_provenance.json',cover)
 auth=read(S/'publication_authorization.json');auth.update(scope='PROPOSED_EXACT_IN_TEXT_READER_CATALOG_AND_COVER_DISPLAY',rights_decision_id=decision_id,cover_provenance_sha256=sha(P/'cover_provenance.json'),cover_status='PENDING_TWO_EXACT_COMPONENT_REVIEWS',cover_provenance_status='PROPOSED_NOT_ACCEPTED',publication_authorized=False,authorized_by='Automated isolated proposal preparation under Oct3 prospective owner delegation; not yet accepted, no human/legal signature inferred.',verified_at=STAMP,release_condition='Fresh independent pixel/delivery/copy/package reviews twice, actual prospective component acceptance, serialized protected release/deployment/canary/readback gates remain required.',audio_authorized=False,production_activation_authorized_by_this_file=False)
 if 'not_authorized' in auth:auth['not_authorized']=['audio_stream','audio_download','other editions','production activation']
 put(P/'publication_authorization.json',auth)
 oldapp=read(S/'approval_evidence.json');put(archive/'original-approval-evidence.json',oldapp)
 app={'slug':slug,'approved_to_publish':False,'rights_tier':oldapp.get('rights_tier','A'),'verification_status':'approved','qa_status':'QA_PASSED','qa_scope':'Exact existing edition-bound text identity/source completeness only; no audio or production observations.','approval_scope':'PROPOSED_EXACT_IN_TEXT_AND_COVER_BINDING_PENDING_TWO_REVIEWS','allowCheckout':False,'allowPayment':False,'audiobook_enabled':False,'audiobook_use_approved':False,'audio_public_release':'PUBLIC_AUDIO_RELEASE_NOT_APPROVED','verified_at':STAMP,'source_hash':source['source_hash'],'content_hash':source['content_hash'],'publication_authorization_sha256':sha(P/'publication_authorization.json'),'cover_provenance_sha256':sha(P/'cover_provenance.json'),'independent_reviews':[]}
 put(P/'approval_evidence.json',app)
 oldbook=read(S/'public_book.json');book={k:v for k,v in oldbook.items() if not k.startswith(('audio','audiobook','generate_audiobook')) and k not in ('candidate_fingerprint','rights_metadata')};put(archive/'removed-public-audio-and-rights-pointers.json',{k:v for k,v in oldbook.items() if k not in book})
 for k in ['cover_url','cover_image_url','coverImage','cover_image']:book[k]=assets['front']['delivery_url']
 for k in ['back_cover_url','back_cover_image_url','backCoverImage']:book[k]=assets['back']['delivery_url']
 book.update(formats=['Ebook'],cover_dimensions={k:a['delivery_dimensions'] for k,a in assets.items()},rights_basis=old['basis'],approved_to_publish=False,publication_status='READY_FOR_ACTIVATION_GLOBAL_GATE',publicationStatus='ready',isPublic=False,isLive=False,is_published=False,showInPublicLibrary=False,showInHomepage=False,allowPublicReading=False,allowCheckout=False,allowPayment=False,audio_enabled=False,audiobook_enabled=False,generate_audiobook=False,audiobook_assets={},audiobook={},cover_status='PENDING_EXACT_COMPONENT_REVIEWS',publication_authorization_sha256=sha(P/'publication_authorization.json'),cover_provenance_sha256=sha(P/'cover_provenance.json'))
 put(P/'public_book.json',book)
 oldreader=read(S/'reader_manifest.json');reader={k:v for k,v in oldreader.items() if not k.startswith(('audio','audiobook','generate_audiobook'))};put(archive/'removed-reader-audio-pointers.json',{k:v for k,v in oldreader.items() if k not in reader});reader.update(audio_enabled=False,audiobook_enabled=False);put(P/'reader_manifest.json',reader)
 checks=read(S/'checksum_manifest.json');checks['generated_at']=STAMP;checks['files']=[{'file':str(f.relative_to(P)),'sha256':sha(f)} for f in sorted(P.rglob('*')) if f.is_file() and f.name not in ('checksum_manifest.json','publication_manifest.json','rights_decision.json')];put(P/'checksum_manifest.json',checks)
 man=read(S/'publication_manifest.json');man['generated_at']=STAMP;man['reader_release'].update(status='READY_FOR_APPROVAL',exposed=False,cover_url=assets['front']['delivery_url'],blockers=['TWO_EXACT_COMPONENT_REVIEWS_AND_ACTUAL_PROSPECTIVE_ACCEPTANCE_REQUIRED']);man['audio_release']={'status':'NOT_REQUESTED','exposed':False,'required_for_reader_release':False};man['artifacts']={f.stem:sha(f) for f in P.glob('*.json') if f.name not in ('rights_decision.json','publication_manifest.json','checksum_manifest.json','highlight_sync.json')};man.pop('manifest_sha256',None);man['manifest_sha256']=canon(man);put(P/'publication_manifest.json',man)
 dec=dict(old);dec.update(decision_id=decision_id,status='PROPOSED',components={f.stem:sha(f) for f in P.glob('*.json') if f.name in ('public_book.json','reader_manifest.json','source_evidence.json','approval_evidence.json','checksum_manifest.json','publication_manifest.json','cover_provenance.json')},uses=['cover_display','catalog_metadata','reader_preview','reader_delivery','reading_pass_session','reading_pass_renewal'],valid_from=STAMP,basis=old['basis']+' Proposed exact owner cover mask/typeset derivatives; fresh2 passing independent reviews and actual automated acceptance remain required.',accepted_by='NOT_ACCEPTED: automated isolated proposal worker under prospective owner authority; no human/legal signature or production observations.',conditions_satisfied=False);put(P/'rights_decision.json',dec)
 for n in ['public_book','reader_manifest','approval_evidence','publication_manifest']:
  text=json.dumps(read(P/(n+'.json'))).lower();assert all(x not in text for x in ['backblazeb2','.mp3','audiobook_active_release','release_descriptor','production_audio_evidence','listening_qa','asr_manuscript','technical_audio_qa','uploaded_artifact_sha256'])
 for f in list((S/'chapters').glob('*.json'))+[S/'source_evidence.json',S/'license_notice.json',S/'highlight_sync.json']:assert sha(P/f.relative_to(S))==sha(f)
 inventory={str(f.relative_to(P)):sha(f) for f in P.rglob('*') if f.is_file()};record={'slug':slug,'status':'FROZEN_UNACCEPTED_PROPOSAL_TWO_FRESH_REVIEWS_REQUIRED','proposal_path':str(P),'source_validation_sha256':sha(out/'source-validation.json'),'cover_preparation_sha256':sha(out/'cover-preparation.json'),'preimage_inventory_sha256':sha(out/'preimage-inventory.json'),'package_inventory':inventory,'package_inventory_canonical_sha256':canon(inventory),'decision_raw_sha256':sha(P/'rights_decision.json'),'decision_canonical_sha256':canon(dec),'removed_archived_components':removed,'source_chapter_license_sync_bytes_unchanged':True,'effective_audio_disabled_claims_clean':True,'actual_acceptance_created':False,'canonical_or_production_mutation':False,'next_action':'Two fresh independent exact typography/copy/delivery/package reviews; PASS permits prospective acceptance paperwork, substantial HOLD causes terminal exclusion without further repair.'};put(out/'validation.json',record);records.append({k:v for k,v in record.items() if k!='package_inventory'})
put(O/'batch-result.json',{'schema':'earnalism.bengali-distinct-next-cohort.v1','titles':records,'source_reinvestigations':0,'original_gets':6,'paid_generation_calls':0,'new_external_tasks':0,'canonical_mutations':0,'actual_acceptance_or_release_created':False});print(json.dumps(records,ensure_ascii=False,indent=2))
