from pathlib import Path
from datetime import datetime,timezone
import hashlib,json,shutil
R=Path('/tmp/earnalism-main-approved-integration');O=Path(__file__).parent;S=R/'data/controlled_publications/the-open-window';P=O/'proposal/data/controlled_publications/the-open-window';B=R/'backend/data/controlled_publications/the-open-window'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
canon=lambda d:hashlib.sha256(json.dumps(d,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
read=lambda p:json.loads(p.read_text())
def put(p,d):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
STAMP=datetime.now(timezone.utc).isoformat();SLUG='the-open-window'
shutil.copytree(S,O/'preimages/root',dirs_exist_ok=True);shutil.copytree(S,P,dirs_exist_ok=True)
if B.exists():shutil.copytree(B,O/'preimages/backend',dirs_exist_ok=True)
pre={role:{str(p.relative_to(O/'preimages'/role)):sha(p) for p in sorted((O/'preimages'/role).rglob('*')) if p.is_file()} for role in ('root','backend')}
old=read(S/'rights_decision.json');oldauth=read(S/'publication_authorization.json');source=read(S/'source_evidence.json')
for k,h in old['components'].items():assert sha(S/(k+'.json'))==h
for x in read(S/'checksum_manifest.json')['files']:
 if x['file']!='checksum_manifest.json':assert sha(S/x['file'])==x['sha256']
ch=read(S/'chapters/chapter-001.json');assert hashlib.sha256(ch['content'].encode()).hexdigest()==ch['content_hash']==oldauth['chapter_sha256']['chapter-001']==source['content_hash']
matrix=read(R/'internal/legal/catalogue_clearance_20261002/english/matrix.json');row=next(x for x in matrix['titles'] if x['slug']==SLUG);assert not row['noncover_gaps'];whole=row['independent_whole_work_boundary_evidence'];assert sha(R/whole['artifact'])==whole['artifact_sha256'];assert whole['coverage_review']['whole_narrative_coverage']=='PASS'
rep=read(O/'repair-receipt.json');rec=read(O/'recovery-receipt.json');assets={}
for kind in ('front','back'):
 d=rep['assets'][kind];orig=O/(kind+'-original.png');png=O/(kind+'-layout-repair.png');webp=O/(kind+'-delivery.webp');assert sha(orig)==d['original_sha256'];assert sha(png)==d['layout_png']['sha256'];assert sha(webp)==d['delivery']['sha256']
 for f in (orig,png,webp):(P/'covers').mkdir(exist_ok=True);shutil.copy2(f,P/'covers'/f.name)
 name=f'{SLUG}-{kind}-{sha(webp)[:8]}.webp';static=O/'proposal/frontend/public/assets/books'/SLUG/name;static.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(webp,static)
 assets[kind]={'original_file':'covers/'+orig.name,'original_sha256':sha(orig),'original_url':next(x['url'] for x in rec['requests'] if x['kind']==kind),'repair_file':'covers/'+png.name,'repair_sha256':sha(png),'delivery_file':'covers/'+webp.name,'delivery_sha256':sha(webp),'delivery_url':'https://theearnalism.com/assets/books/'+SLUG+'/'+name,'delivery_bytes':webp.stat().st_size,'production_observed':False}
owner='internal/legal/bengali_text_preparation_20261002/evidence_matrix.json';assert 'Owner states all front and back covers are designed by the owner.' in (R/owner).read_text()
cover={'schema':'earnalism.cover-provenance.v1','slug':SLUG,'status':'PROPOSED_EXACT_COMPONENT_BINDING_PENDING_TWO_INDEPENDENT_REVIEWS','original_creator':'Repository/product owner; no additional identity inferred','owner_declaration':{'statement':'Owner states all front and back covers are designed by the owner.','path':owner,'sha256':sha(R/owner),'scope':'Cover design only; not text rights or runtime release'},'owner_delegation':'Existing issue477 comment5949652699 and explicit prospective Oct3 owner instruction superseding procedural cover deferral. This proposal does not record acceptance before fresh passing reviews.','source_sha256':source['source_hash'],'content_sha256':source['content_hash'],'assets':assets,'derivative_lineage':{'recovery_receipt_sha256':sha(O/'recovery-receipt.json'),'repair_receipt_sha256':sha(O/'repair-receipt.json'),'renderer_sha256':sha(O/'render.py'),'method':rep['method'],'source_excerpt':rep['source_excerpt'],'no_lexical_changes':True,'new_art':False,'one_bounded_remediation_attempt':1},'visual_review_status':'PENDING_TWO_INDEPENDENT_EXACT_DELIVERY_REPAIR_REVIEWS','commercial_use_authorized':False,'audio_authorized':False,'runtime_release_authorized':False,'production_observed':False}
put(P/'cover_provenance.json',cover)
decision_id='india-20261003-the-open-window-pg269-exact-text-cover'
auth=dict(oldauth);auth.update(scope='PROPOSED_TEXT_READER_CATALOG_METADATA_AND_EXACT_COVER_DISPLAY',rights_decision_id=decision_id,cover_provenance_sha256=sha(P/'cover_provenance.json'),cover_status='PENDING_TWO_INDEPENDENT_REVIEWS',publication_authorized=False,verified_at=STAMP,authorized_by='Automated isolated proposal preparation under prospective owner delegation; acceptance pending exact passing reviews.',not_authorized=['audio_stream','audio_download','other editions','production activation'],existing_text_scope_preserved='TEXT_READER_ONLY_NON_COVER_COMPONENTS',release_condition='Proposal only, not a new effective acceptance. Two fresh independent repair/delivery/package reviews, actual prospective automated component acceptance and serialized protected release gates required.')
put(P/'publication_authorization.json',auth)
approval=read(S/'approval_evidence.json');approval.update(historical_text_approval_preserved=read(S/'approval_evidence.json'),approved_to_publish=False,approval_scope='PROPOSED_OWNER_DELEGATED_EXACT_COMPONENT_BINDING_PENDING_REVIEWS',audiobook_enabled=False,audiobook_use_approved=False,audiobook_use_approval_source='',audiobook_use_approved_at='',audio_public_release='PUBLIC_AUDIO_RELEASE_NOT_APPROVED',audio_qa_status='',provider='',version='',endpoint_url='',verified_at=STAMP,publication_authorization_sha256=sha(P/'publication_authorization.json'),cover_provenance_sha256=sha(P/'cover_provenance.json'),independent_reviews=[])
put(P/'approval_evidence.json',approval)
book=read(S/'public_book.json');historical={k:v for k,v in book.items() if k.startswith(('audio','audiobook','generate_audiobook'))}
book={k:v for k,v in book.items() if not k.startswith(('audio','audiobook','generate_audiobook'))}
for k in ('cover_url','cover_image_url','coverImage','cover_image'):book[k]=assets['front']['delivery_url']
for k in ('back_cover_url','back_cover_image_url','backCoverImage'):book[k]=assets['back']['delivery_url']
book.update(publication_status='READY_FOR_ACTIVATION_GLOBAL_GATE',publicationStatus='ready',isPublic=False,isLive=False,showInPublicLibrary=False,showInHomepage=False,allowPublicReading=False,is_published=False,allowCheckout=False,allowPayment=False,audio_enabled=False,audiobook_enabled=False,generate_audiobook=False,audiobook_assets={},audiobook={},cover_status='PENDING_EXACT_COMPONENT_REVIEW',publication_authorization_sha256=sha(P/'publication_authorization.json'),cover_provenance_sha256=sha(P/'cover_provenance.json'))
book['formats']=['Ebook'];book.pop('candidate_fingerprint',None)
put(P/'public_book.json',book);put(O/'historical-audio-preimage.json',historical)
reader={k:v for k,v in read(S/'reader_manifest.json').items() if not k.startswith(('audio','audiobook','generate_audiobook'))};reader.update(audio_enabled=False,audiobook_enabled=False);put(P/'reader_manifest.json',reader)
checksum=read(S/'checksum_manifest.json');checksum['generated_at']=STAMP;checksum['files']=[{'file':str(f.relative_to(P)),'sha256':sha(f)} for f in sorted(P.rglob('*')) if f.is_file() and f.name not in ('checksum_manifest.json','publication_manifest.json','rights_decision.json')];put(P/'checksum_manifest.json',checksum)
man=read(S/'publication_manifest.json');man['generated_at']=STAMP;man['reader_release'].update(status='READY_FOR_APPROVAL',exposed=False,cover_url=assets['front']['delivery_url'],blockers=['TWO_FRESH_EXACT_REPAIR_DELIVERY_PACKAGE_REVIEWS_AND_ACTUAL_ACCEPTANCE_REQUIRED']);man['audio_release'].update(status='NOT_REQUESTED',exposed=False,required_for_reader_release=False);man['artifacts']={f.stem:sha(f) for f in P.glob('*.json') if f.name not in ('rights_decision.json','publication_manifest.json','checksum_manifest.json','highlight_sync.json')};man.pop('manifest_sha256',None);man['manifest_sha256']=canon(man);put(P/'publication_manifest.json',man)
decision=dict(old);decision.update(decision_id=decision_id,status='PROPOSED',components={f.stem:sha(f) for f in P.glob('*.json') if f.name in ('public_book.json','reader_manifest.json','source_evidence.json','approval_evidence.json','checksum_manifest.json','publication_manifest.json','cover_provenance.json')},uses=['cover_display','catalog_metadata','reader_preview','reader_delivery','reading_pass_session','reading_pass_renewal'],valid_from=STAMP,basis=old['basis']+' Proposed exact existing owner-art bounded repair; prospective cover acceptance pending fresh2 independent reviews. Prior text decision preserved.',accepted_by='NOT_ACCEPTED: isolated automated proposal-preparation worker; no human/legal signature or production observation.',conditions_satisfied=False);put(P/'rights_decision.json',decision)
put(O/'preimage-inventory.json',pre)
put(O/'validation.json',{'slug':SLUG,'status':'PROPOSAL_IDENTITY_PASS_PENDING_FRESH_TWO_INDEPENDENT_REVIEWS','original_components_pass':len(old['components']),'original_checksums_pass':len(read(S/'checksum_manifest.json')['files']),'chapter_count':1,'chapter_content_sha256':ch['content_hash'],'existing_source_fullwork_evidence':whole,'source_unchanged':sha(P/'source_evidence.json')==sha(S/'source_evidence.json'),'chapter_unchanged':sha(P/'chapters/chapter-001.json')==sha(S/'chapters/chapter-001.json'),'audio_historical_claims_archived_not_exposed':True,'assets':assets,'proposed_components':decision['components'],'rights_decision_raw_sha256':sha(P/'rights_decision.json'),'rights_decision_canonical_sha256':canon(decision),'actual_acceptance_created':False,'registry_allowlist_production_mutations':False,'backend_preimage_present':B.exists(),'next_action':'Two fresh independent exact repair/WebP/copy/package reviews. If PASS, create actual prospective acceptance and update dependent hashes before new binding validation; if HOLD, terminal exclusion since one bounded repair exhausted.'})
print(json.dumps({'proposal':str(P),'validation_sha256':sha(O/'validation.json'),'backend_preimage_present':B.exists()},indent=2))
