// Native Reader/AuthProvider/API code; no replacement modules or response mocks.
import fs from 'node:fs';import http from 'node:http';
import path from 'node:path';
import os from 'node:os';import {fileURLToPath} from 'node:url';
const harnessRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
import {createRequire} from 'node:module';
import {execFileSync} from 'node:child_process';
const target=process.env.PERF_READER_WORKTREE;
const evidenceOutput=process.env.PERF_READER_OUTPUT || '/tmp/earnalism-reader-e2e-completion.json';
const uatBase=process.env.UAT_BASE_URL;
const api=process.env.UAT_API_BASE_URL;
if(!target || !uatBase || !api || !uatBase.startsWith('http://127.0.0.1:') || !api.startsWith('http://127.0.0.1:') || process.env.ENVIRONMENT!=='uat')throw Error('Explicit disposable UAT and read-only Reader worktree required');
const pidText=fs.readFileSync(path.join(harnessRoot,'uat/runtime/system-uat/backend.pid'),'utf8');
const pidFields=Object.fromEntries(pidText.trim().split('\n').map(row=>{const index=row.indexOf('=');return[row.slice(0,index),row.slice(index+1)]}));
if(pidFields.category!=='backend'||Number(pidFields.port)!==Number(new URL(api).port)||fs.realpathSync(pidFields.worktree)!==fs.realpathSync(harnessRoot))throw Error('Repository-owned disposable UAT backend required');
process.kill(Number(pidFields.pid),0);
const require=createRequire(path.join(target,'frontend/package.json'));
const webpack=require('webpack'),{chromium}=require('playwright');
const modules=path.join(target,'frontend/node_modules');
const output=fs.mkdtempSync(path.join(os.tmpdir(),'reader-e2e-bundle-'));const staticRoot=path.join(target,'frontend/build');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'reader-real-entry-'));
const entry=path.join(temp,'entry.jsx');
fs.writeFileSync(entry,`import React from 'react';import {createRoot} from 'react-dom/client';import {BrowserRouter,Routes,Route} from 'react-router-dom';import Reader from ${JSON.stringify(path.join(target,'frontend/src/experiences-v2/reader/ReaderExperienceV2Route.jsx'))};import {AuthProvider,useAuth} from ${JSON.stringify(path.join(target,'frontend/src/context/AuthContext.jsx'))};function Control(){const auth=useAuth();return <main><button onClick={()=>auth.userSignup('Disposable E2E Reader','reader-e2e-'+Date.now()+'@example.com',crypto.randomUUID()+'aA7!')}>Create disposable reader</button><output data-testid="identity">{auth.user?.id||'anonymous'}</output></main>}createRoot(document.getElementById('root')).render(<BrowserRouter><AuthProvider><Routes><Route path="/reader/:slug" element={<Reader/>}/><Route path="*" element={<Control/>}/></Routes></AuthProvider></BrowserRouter>);`);
await new Promise((resolve,reject)=>webpack({mode:'production',devtool:false,entry,output:{path:output,filename:'perf-reader-entry.js'},resolve:{modules:[modules],extensions:['.js','.jsx']},module:{rules:[{test:/\.[jt]sx?$/,exclude:/node_modules/,use:{loader:path.join(modules,'babel-loader'),options:{presets:[[path.join(modules,'@babel/preset-react'),{runtime:'automatic'}]]}}},{test:/\.css$/,use:[path.join(modules,'style-loader'),path.join(modules,'css-loader')]}]},plugins:[new webpack.DefinePlugin({'process.env':JSON.stringify({NODE_ENV:'production',REACT_APP_UAT_LOCAL:'true',REACT_APP_BACKEND_URL:''})})]},(e,s)=>e||s.hasErrors()?reject(e||Error(s.toString({all:false,errors:true}))):resolve()));
const manifest=JSON.parse(fs.readFileSync(path.join(staticRoot,'asset-manifest.json')));
fs.writeFileSync(path.join(output,'perf-reader.html'),`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="${manifest.files['main.css']}"></head><body><div id="root"></div><script src="/perf-reader-entry.js"></script></body></html>`);

let delayed=false;let delayedRequests=0;let disconnectedResponses=0;
const proxy=http.createServer((req,res)=>{
 const pathname=new URL(req.url,'http://localhost').pathname;
 if(pathname==='/__test/delay'){delayed=new URL(req.url,'http://localhost').searchParams.get('on')==='1';res.end('ok');return;}
 if(pathname.startsWith('/api/')){const upstream=http.request(api.replace(/\/api$/,'')+req.url,{method:req.method,headers:{...req.headers,host:new URL(api).host}},r=>{const slow=delayed && /\/pages\/[4-9]\d*$/.test(pathname);if(slow){delayedRequests++;let chunks=[];r.on('data',x=>chunks.push(x));r.on('end',()=>{const timer=setTimeout(()=>{if(!res.destroyed){res.writeHead(r.statusCode,r.headers);res.end(Buffer.concat(chunks));}chunks=[]},1500);res.on('close',()=>{if(!res.writableEnded){disconnectedResponses++;clearTimeout(timer);chunks=[]}})});}else{res.writeHead(r.statusCode,r.headers);r.pipe(res)}});upstream.on('error',()=>{if(!res.destroyed)res.writeHead(502).end()});req.pipe(upstream);req.on('aborted',()=>upstream.destroy());return;}
 const root=pathname.startsWith('/static/')||pathname.startsWith('/assets/')?staticRoot:output;let file=path.resolve(root,'.'+pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}if(!fs.existsSync(file)||!fs.statSync(file).isFile())file=path.join(output,'perf-reader.html');res.setHeader('content-type',({'.js':'text/javascript','.css':'text/css','.woff2':'font/woff2','.html':'text/html','.png':'image/png','.svg':'image/svg+xml','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));
});
await new Promise(resolve=>proxy.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+proxy.address().port;
console.error('NATIVE_BENCH_BASE='+base);
const evidence={scope:'REAL_DISPOSABLE_BACKEND_NATIVE_READER_AUTH_PROVIDER_NO_API_MOCKS',frontend_head:execFileSync('git',['-C',target,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),frontend_patch_sha256:(await import('node:crypto')).createHash('sha256').update(execFileSync('git',['-C',target,'diff','--','frontend/src/experiences-v2/reader/visualPagination.js'])).digest('hex'),backend_head:execFileSync('git',['-C',harnessRoot,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),loads:[],turns:[],memory:[],resize:[],chapters:[],network:[],errors:[],production_changed:false,limits:['Reader component and AuthProvider use a thin route shell, not the full application startup bundle.','Read-only repository-controlled Dracula manuscript; disposable wallet credits, normal signup/session/lease handlers.','Application-local cache entries are not exposed; cache-hit dataset and documented four-entry bound reported separately.','Exact assembly/React commit milestones not instrumented in application code: dataset durations reported without invented absolute stage timestamps.']};
const browser=await chromium.launch({headless:true});evidence.browser=browser.version();
const stats=values=>{const x=[...values].sort((a,b)=>a-b);return{samples:x.length,p50:x[Math.floor((x.length-1)*.5)],p95:x[Math.ceil((x.length-1)*.95)],max:x.at(-1),...(x.length>=100?{p99:x[Math.ceil((x.length-1)*.99)]}:{})}};
const waitFn=async(page,fn,arg,timeout=30000)=>{const handle=await page.waitForFunction(fn,arg,{timeout});await handle.dispose()};
const route=async(page,url)=>page.evaluate(u=>{history.pushState({},'',u);dispatchEvent(new PopStateEvent('popstate'))},url);
const ready=async page=>{const consent=page.getByRole('button',{name:'Continue to this page',exact:true});await consent.or(page.getByTestId('reader-reading-text')).first().waitFor({timeout:45000});if(await consent.count())await consent.click();await page.locator('[data-pagination-ready="true"]').waitFor({timeout:60000});await page.getByTestId('reader-reading-text').waitFor();};
const sample=page=>page.evaluate(()=>{const n=document.querySelector('.reader-v2__visual-viewport'),t=document.querySelector('[data-testid="reader-reading-text"]');return{dataset:n?{...n.dataset}:null,clientHeight:n?.clientHeight,scrollHeight:n?.scrollHeight,overflow:n?n.scrollHeight>n.clientHeight+2:null,mountedPages:document.querySelectorAll('[data-testid="reader-reading-text"]').length,opening:!!document.querySelector('.reader-opening'),sourceAnchor:n?{chapter:n.dataset.chapterId,page:n.dataset.sourcePage,offset:n.dataset.sourceOffset}:null,textCharacters:t?.textContent.length}});
const instrument=()=>{const audit={events:[],timers:new Map(),rafs:new Set(),observers:[],longTasks:[],digests:[],states:[]};window.__readerAudit=audit;for(const name of ['ResizeObserver','MutationObserver','IntersectionObserver']){const Native=window[name];if(!Native)continue;window[name]=class extends Native{constructor(cb){super(cb);this.auditActive=true;audit.observers.push({kind:name,ref:new WeakRef(this)})}disconnect(){this.auditActive=false;return super.disconnect()}}};for(const [set,clear,kind] of [['setTimeout','clearTimeout','timeout'],['setInterval','clearInterval','interval']]){const s=window[set],c=window[clear];window[set]=(cb,ms,...args)=>{let id=s(()=>{if(kind==='timeout')audit.timers.delete(id);cb(...args)},ms);audit.timers.set(id,kind);return id};window[clear]=id=>{audit.timers.delete(id);return c(id)}};const r=window.requestAnimationFrame,c=window.cancelAnimationFrame;window.requestAnimationFrame=cb=>{let id=r(t=>{audit.rafs.delete(id);cb(t)});audit.rafs.add(id);return id};window.cancelAnimationFrame=id=>{audit.rafs.delete(id);return c(id)};const digest=crypto.subtle.digest.bind(crypto.subtle);crypto.subtle.digest=async(...args)=>{const start=performance.now();const result=await digest(...args);audit.digests.push({at:start,duration:performance.now()-start});return result};document.fonts?.ready.then(()=>audit.fontsReady=performance.now());new PerformanceObserver(list=>{audit.longTasks.push(...list.getEntries().map(e=>({at:e.startTime,duration:e.duration})));if(audit.longTasks.length>500)audit.longTasks.splice(0,audit.longTasks.length-500)}).observe({type:'longtask',buffered:true});};
let activeContext;
try{
 const seed=await browser.newContext();let seedPage=await seed.newPage();await seedPage.goto(base+'/perf-reader.html');await seedPage.getByRole('button',{name:'Create disposable reader'}).click();await waitFn(seedPage,()=>document.querySelector('[data-testid="identity"]')?.textContent!=='anonymous');const id=await seedPage.getByTestId('identity').innerText();execFileSync(path.join(harnessRoot,'.venv-uat/bin/python'),['-c',"import sys;from pymongo import MongoClient;c=MongoClient('mongodb://127.0.0.1:27018/earnalism_uat?replicaSet=earnalism-uat-rs0');r=c.earnalism_uat.users.update_one({'id':sys.argv[1]},{'$set':{'reading_seconds_balance':20000,'wallet_seconds':20000}});assert r.matched_count==1;c.close()",id],{stdio:'pipe'});await seedPage.evaluate(()=>localStorage.setItem('earnalism_reading_pass_device_v1',crypto.randomUUID()));const storage=await seed.storageState();await seed.close();
 const preview=await browser.newContext();const guest=await preview.newPage();const previewRequests=[];guest.on('request',r=>{const m=new URL(r.url()).pathname.match(/\/pages\/(\d+)$/);if(m)previewRequests.push(Number(m[1]))});await guest.goto(base+'/reader/dracula?p=1');await ready(guest);const deny=await preview.request.get(base+'/api/reading-pass/books/dracula/pages/4');evidence.preview={requested_pages:previewRequests,unauthorized_chunk_requests:previewRequests.filter(n=>n>3).length,protected_status:deny.status(),...await sample(guest)};await preview.close();if(deny.status()!==401||evidence.preview.unauthorized_chunk_requests)throw Error('Preview security failure');
 for(const [width,height] of [[1440,900],[390,844],[844,390]]){
  let context;let page;let requests;const attach=async()=>{context=await browser.newContext({viewport:{width,height},storageState:storage});activeContext=context;await context.addInitScript(instrument);page=await context.newPage();requests=[];const ids=new WeakMap();page.on('pageerror',e=>evidence.errors.push(e.message));page.on('request',r=>{const u=new URL(r.url());const row={path:u.pathname,at:Date.now(),method:r.method(),lease_present:!!r.headers()['x-reading-pass-lease']};ids.set(r,requests.length);requests.push(row)});page.on('response',r=>{const i=ids.get(r.request());if(i!==undefined){requests[i].status=r.status();requests[i].responseAt=Date.now();requests[i].cacheControl=r.headers()['cache-control']}});page.on('requestfinished',r=>{const i=ids.get(r);if(i!==undefined){requests[i].completedAt=Date.now();const sizes=r.sizes();sizes.then(s=>requests[i].bytes=s.responseBodySize).catch(()=>{})}});page.on('requestfailed',r=>{const i=ids.get(r);if(i!==undefined){requests[i].aborted=/ABORT|CANCEL/i.test(r.failure()?.errorText||'');requests[i].failed=true}});return page};
  for(const kind of ['cold','warm']){for(let iteration=0;iteration<(kind==='cold'?10:20);iteration++){
   await new Promise(r=>setTimeout(r,5500));if(kind==='cold'||iteration===0)await attach();const before=requests.length;const started=Date.now();await page.goto(base+'/reader/dracula?p=4');await ready(page);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const elapsed=Date.now()-started;const s=await sample(page);const calls=requests.slice(before).filter(r=>r.path.startsWith('/api/'));evidence.loads.push({width,height,kind,iteration,firstReadableMs:elapsed,...s,stage_requests:calls,stages:await page.evaluate(()=>({fontsReady:window.__readerAudit.fontsReady,digests:window.__readerAudit.digests.slice(-20),longTasks:window.__readerAudit.longTasks}))});if(s.overflow)throw Error('Central Reader overflow');console.error(kind+' '+width+' '+iteration+' '+elapsed+'ms');
   if(kind==='cold'){await route(page,'/perf-reader.html');await page.getByTestId('identity').waitFor();await page.waitForTimeout(300);await context.close();}else if(iteration!==19){await route(page,'/perf-reader.html');await page.getByTestId('identity').waitFor();await page.waitForTimeout(100)}
  }}
  const cdp=await context.newCDPSession(page);await cdp.send('Performance.enable');const beforeMetrics=(await cdp.send('Performance.getMetrics')).metrics;const times=[];
  for(let i=0;i<100;i++){await page.waitForTimeout(1500);const old=(await sample(page)).dataset.visualPageIndex;const button=page.getByRole('button',{name:i%2?'Previous page':'Next page',exact:true});const t=performance.now();await button.click();await waitFn(page,old=>document.querySelector('.reader-v2__visual-viewport')?.dataset.visualPageIndex!==old && document.querySelector('.reader-v2__visual-viewport')?.dataset.paginationReady==='true',old);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));times.push(performance.now()-t);await waitFn(page,()=>[...document.querySelectorAll('.reader-v2__page-content')].every(n=>n.getAnimations().every(a=>a.playState!=='running')));}
  evidence.turns.push({width,height,latency:stats(times),metricBefore:beforeMetrics,metricAfter:(await cdp.send('Performance.getMetrics')).metrics,semantics:'Input to destination DOM plus two animation frames; not transition-completion duration'});
  const before=await sample(page);for(const [w,h] of [[390,844],[844,390],[1440,900]]){const started=performance.now();await page.setViewportSize({width:w,height:h});await page.waitForTimeout(120);await page.locator('[data-pagination-ready="true"]').waitFor();evidence.resize.push({from:[width,height],to:[w,h],elapsed:performance.now()-started,beforeAnchor:before.sourceAnchor,...await sample(page)})}
  for(const name of ['Increase text size','Decrease text size']){const start=performance.now();await page.getByRole('button',{name,exact:true}).first().click();await page.waitForTimeout(120);await page.locator('[data-pagination-ready="true"]').waitFor();evidence.resize.push({action:name,elapsed:performance.now()-start,...await sample(page)})}
  evidence.network.push({width,height,requests:requests.filter(r=>r.path.startsWith('/api/')),longTasks:await page.evaluate(()=>window.__readerAudit.longTasks)});await route(page,'/perf-reader.html');await page.getByTestId('identity').waitFor();await page.waitForTimeout(500);await context.close();activeContext=null;
 }
 const context=await browser.newContext({viewport:{width:1440,height:900},storageState:storage});activeContext=context;await context.addInitScript(instrument);const page=await context.newPage();const cdp=await context.newCDPSession(page);await cdp.send('Performance.enable');const collect=async(cycle,arm)=>{await cdp.send('HeapProfiler.collectGarbage');await cdp.send('HeapProfiler.collectGarbage');const metrics=(await cdp.send('Performance.getMetrics')).metrics;let row={cycle,arm,heap:metrics.find(m=>m.name==='JSHeapUsedSize')?.value,...await cdp.send('Memory.getDOMCounters'),...await sample(page),...await page.evaluate(()=>({activeObservers:window.__readerAudit.observers.filter(x=>x.ref.deref()?.auditActive).reduce((a,x)=>(a[x.kind]=(a[x.kind]||0)+1,a),{}),timers:window.__readerAudit.timers.size,rafs:window.__readerAudit.rafs.size}))};if([0,5,10,15].includes(cycle)){let chunks=[];const listener=x=>chunks.push(x.chunk);cdp.on('HeapProfiler.addHeapSnapshotChunk',listener);await cdp.send('HeapProfiler.takeHeapSnapshot',{reportProgress:false});cdp.off('HeapProfiler.addHeapSnapshotChunk',listener);const heap=JSON.parse(chunks.join(''));chunks=[];const f=heap.snapshot.meta.node_fields,step=f.length,di=f.indexOf('detachedness');let detached=0;for(let n=0;n<heap.nodes.length;n+=step)if(heap.nodes[n+di]===2)detached++;row.detachedNodes=detached;}return row};
 await page.goto(base+'/perf-reader.html');evidence.memory.push(await collect(0,'control'));for(let i=1;i<=15;i++){for(const u of ['/library','/detail','/library','/perf-reader.html'])await route(page,u);await page.getByTestId('identity').waitFor();await page.waitForTimeout(300);evidence.memory.push(await collect(i,'control'))}
 evidence.memory.push(await collect(0,'reader'));
 for(let i=1;i<=15;i++){
  await page.waitForTimeout(15000);await route(page,'/reader/dracula?p=4');await ready(page);for(let k=0;k<6;k++){await page.getByRole('button',{name:k%2?'Previous page':'Next page',exact:true}).click();await page.waitForTimeout(1500);await page.locator('[data-pagination-ready="true"]').waitFor();}
  const manifest=await page.evaluate(async()=>{const r=await fetch('/api/reader/book/dracula/manifest',{headers:{Authorization:'Bearer '+localStorage.getItem('earnalism_user_token')}});return r.json()});const later=manifest.canonical_pages.pages.find(x=>x.chapter_id==='chapter-002')?.page_number;if(!later)throw Error('Second chapter missing');await route(page,'/reader/dracula?p='+later);await ready(page);evidence.chapters.push({cycle:i,to:'chapter-002',...await sample(page)});await route(page,'/reader/dracula?p=4');await ready(page);evidence.chapters.push({cycle:i,to:'chapter-001',...await sample(page)});await page.setViewportSize({width:i%2?390:1440,height:i%2?844:900});await page.waitForTimeout(120);await page.locator('[data-pagination-ready="true"]').waitFor();if(i===1){const b=page.getByRole('button',{name:'Bookmark this page',exact:true}).first();if(await b.count())await b.click();}
  await route(page,'/perf-reader.html');await page.getByTestId('identity').waitFor();await page.waitForTimeout(300);evidence.memory.push(await collect(i,'reader'));console.error('memory cycle '+i);
 }
 await page.goto(base+'/__test/delay?on=1');await page.goto(base+'/reader/dracula?p=4');const consent=page.getByRole('button',{name:'Continue to this page',exact:true});await consent.waitFor();let failures=0;let started=0;let completed=0;page.on('request',r=>{if(/\/pages\/[4-9]\d*$/.test(r.url()))started++});page.on('requestfailed',r=>{if(/\/pages\/[4-9]\d*$/.test(r.url()))failures++});page.on('requestfinished',r=>{if(/\/pages\/[4-9]\d*$/.test(r.url()))completed++});await consent.click();await page.waitForTimeout(100);await route(page,'/perf-reader.html');await page.getByTestId('identity').waitFor();await page.waitForTimeout(1800);evidence.cancellation={requests_started:started,requests_completed:completed,requests_aborted:failures,delayedRequests,disconnectedResponses,stale_responses_applied:await page.getByTestId('reader-reading-text').count()};await context.close();activeContext=null;
}catch(e){evidence.failure=e.message;if(activeContext){const p=activeContext.pages().at(-1);evidence.failureState=await p.evaluate(()=>({path:location.pathname,heading:document.querySelector('h1,h2')?.textContent,pagination:document.querySelector('.reader-v2__visual-viewport')?.dataset.paginationError})).catch(()=>null);}process.exitCode=1;console.error('FAILED '+e.message)}finally{if(activeContext)await activeContext.close();await browser.close();await new Promise(r=>proxy.close(r));fs.writeFileSync(evidenceOutput,JSON.stringify(evidence,null,2));}
