// Native Reader/AuthProvider/API code; no replacement modules or response mocks.
import fs from 'node:fs';import http from 'node:http';
import path from 'node:path';
import os from 'node:os';import {fileURLToPath} from 'node:url';
const harnessRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
import {createRequire} from 'node:module';
import {execFileSync} from 'node:child_process';
import {summarizeReaderTrace} from './reader_trace_summary.mjs';
const target=process.env.PERF_READER_WORKTREE;
const evidenceOutput=process.env.PERF_READER_OUTPUT || '/tmp/earnalism-reader-final-acceptance.json';
const uatBase=process.env.UAT_BASE_URL;
const api=process.env.UAT_API_BASE_URL;
if(!target || !uatBase || !api || !uatBase.startsWith('http://127.0.0.1:') || !api.startsWith('http://127.0.0.1:') || process.env.ENVIRONMENT!=='uat')throw Error('Explicit disposable UAT and read-only Reader worktree required');
const pidText=fs.readFileSync(path.join(harnessRoot,'uat/runtime/system-uat/backend.pid'),'utf8');
const pidFields=Object.fromEntries(pidText.trim().split('\n').map(row=>{const index=row.indexOf('=');return[row.slice(0,index),row.slice(index+1)]}));
if(pidFields.category!=='backend'||Number(pidFields.port)!==Number(new URL(api).port)||fs.realpathSync(pidFields.worktree)!==fs.realpathSync(harnessRoot))throw Error('Repository-owned disposable UAT backend required');
process.kill(Number(pidFields.pid),0);
if(execFileSync('git',['-C',target,'rev-parse','HEAD'],{encoding:'utf8'}).trim()!=='0a242584c438a0da8160ea502e421161b039d0fe'||execFileSync('git',['-C',target,'status','--porcelain','--untracked-files=no'],{encoding:'utf8'}).trim())throw Error('Clean exact Reader head required');
const require=createRequire(path.join(target,'frontend/package.json'));
const webpack=require('webpack'),{chromium}=require('playwright');
const modules=path.join(target,'frontend/node_modules');
const output=fs.mkdtempSync(path.join(os.tmpdir(),'reader-e2e-bundle-'));const staticRoot=path.join(target,'frontend/build');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'reader-real-entry-'));
const entry=path.join(temp,'entry.jsx');
fs.writeFileSync(entry,`import React from 'react';import {createRoot} from 'react-dom/client';import {BrowserRouter,Routes,Route} from 'react-router-dom';import Reader from ${JSON.stringify(path.join(target,'frontend/src/experiences-v2/reader/ReaderExperienceV2Route.jsx'))};import {AuthProvider,useAuth} from ${JSON.stringify(path.join(target,'frontend/src/context/AuthContext.jsx'))};function Control(){const auth=useAuth();return <main><button onClick={()=>auth.userSignup('Disposable E2E Reader','reader-e2e-'+Date.now()+'@example.com',crypto.randomUUID()+'aA7!')}>Create disposable reader</button><output data-testid="identity">{auth.user?.id||'anonymous'}</output></main>}createRoot(document.getElementById('root')).render(<BrowserRouter><AuthProvider><Routes><Route path="/reader/:slug" element={<Reader/>}/><Route path="*" element={<Control/>}/></Routes></AuthProvider></BrowserRouter>);`);
await new Promise((resolve,reject)=>webpack({mode:'production',devtool:false,entry,output:{path:output,filename:'perf-reader-entry.js'},resolve:{modules:[modules],extensions:['.js','.jsx']},module:{rules:[{test:/\.[jt]sx?$/,exclude:/node_modules/,use:[{loader:path.join(modules,'babel-loader'),options:{presets:[[path.join(modules,'@babel/preset-react'),{runtime:'automatic'}]]}},path.join(harnessRoot,'scripts/reader_stage_loader.cjs')]},{test:/\.css$/,use:[path.join(modules,'style-loader'),path.join(modules,'css-loader')]}]},plugins:[new webpack.DefinePlugin({'process.env':JSON.stringify({NODE_ENV:'production',REACT_APP_UAT_LOCAL:'true',REACT_APP_BACKEND_URL:''})})]},(e,s)=>e||s.hasErrors()?reject(e||Error(s.toString({all:false,errors:true}))):resolve()));
const manifest=JSON.parse(fs.readFileSync(path.join(staticRoot,'asset-manifest.json')));
fs.writeFileSync(path.join(output,'perf-reader.html'),`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="${manifest.files['main.css']}"></head><body><div id="root"></div><script src="/perf-reader-entry.js"></script></body></html>`);

let delayed=false;let delayedRequests=0;let disconnectedResponses=0;
const proxy=http.createServer((req,res)=>{
 const pathname=new URL(req.url,'http://localhost').pathname;
 if(pathname==='/__test/delay'){delayed=new URL(req.url,'http://localhost').searchParams.get('on')==='1';res.end('ok');return;}
 if(pathname.startsWith('/api/')){const upstream=http.request(api.replace(/\/api$/,'')+req.url,{method:req.method,headers:{...req.headers,host:new URL(api).host}},r=>{const slow=delayed && /\/pages\/[4-9]\d*$/.test(pathname);if(slow){delayedRequests++;let chunks=[];r.on('data',x=>chunks.push(x));r.on('end',()=>{const timer=setTimeout(()=>{if(!res.destroyed){res.writeHead(r.statusCode,r.headers);res.end(Buffer.concat(chunks));}chunks=[]},1500);res.on('close',()=>{if(!res.writableEnded){disconnectedResponses++;clearTimeout(timer);chunks=[]}})});}else{res.writeHead(r.statusCode,r.headers);r.pipe(res)}});upstream.on('error',()=>{if(!res.destroyed)res.writeHead(502).end()});req.pipe(upstream);req.on('aborted',()=>upstream.destroy());return;}
 const root=pathname.startsWith('/static/')||pathname.startsWith('/assets/')?staticRoot:output;let file=path.resolve(root,'.'+pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}if(!fs.existsSync(file)||!fs.statSync(file).isFile())file=path.join(output,'perf-reader.html');res.setHeader('content-type',({'.js':'text/javascript','.css':'text/css','.woff2':'font/woff2','.html':'text/html','.png':'image/png','.svg':'image/svg+xml','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));
});
await new Promise(resolve=>proxy.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+proxy.address().port;
console.error('NATIVE_BENCH_BASE='+base);
const evidence={scope:'REAL_DISPOSABLE_BACKEND_NATIVE_READER_AUTH_PROVIDER_NO_API_MOCKS',frontend_head:execFileSync('git',['-C',target,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),frontend_patch_sha256:(await import('node:crypto')).createHash('sha256').update(execFileSync('git',['-C',target,'diff','--','frontend/src/experiences-v2/reader/visualPagination.js'])).digest('hex'),backend_head:execFileSync('git',['-C',harnessRoot,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),loads:[],turns:[],memory:[],resize:[],chapters:[],network:[],errors:[],production_changed:false,limits:['Reader component and AuthProvider use a thin route shell, not the full application startup bundle.','Read-only repository-controlled Dracula manuscript; disposable wallet credits, normal signup/session/lease handlers.','Application-local cache entries are not exposed; cache-hit dataset and documented four-entry bound reported separately.','Benchmark-only compile transform marks actual pipeline; no product source modified. T0=document start. Fresh context cold, same-context reload warm; backend caches not flushed.']};
const browser=await chromium.launch({headless:true});evidence.browser=browser.version();
const stats=values=>{const x=[...values].sort((a,b)=>a-b);const quant=p=>x[Math.ceil((x.length-1)*p)];return{samples:x.length,median:x.length%2?x[(x.length-1)/2]:(x[x.length/2-1]+x[x.length/2])/2,p90:quant(.9),p95:quant(.95),max:x.at(-1)}};
const waitFn=async(page,fn,arg,timeout=30000)=>{const handle=await page.waitForFunction(fn,arg,{timeout});await handle.dispose()};
const route=async(page,url)=>page.evaluate(u=>{history.pushState({},'',u);dispatchEvent(new PopStateEvent('popstate'))},url);
const ready=async page=>{const consent=page.getByRole('button',{name:'Continue to this page',exact:true});await consent.or(page.getByTestId('reader-reading-text')).first().waitFor({timeout:45000});if(await consent.count())await consent.click();await page.locator('[data-pagination-ready="true"]').waitFor({timeout:60000});await page.getByTestId('reader-reading-text').waitFor();};
const sample=page=>page.evaluate(()=>{const n=document.querySelector('.reader-v2__visual-viewport'),t=document.querySelector('[data-testid="reader-reading-text"]');return{dataset:n?{...n.dataset}:null,clientHeight:n?.clientHeight,scrollHeight:n?.scrollHeight,overflow:n?n.scrollHeight>n.clientHeight+2:null,mountedPages:document.querySelectorAll('[data-testid="reader-reading-text"]').length,opening:!!document.querySelector('.reader-opening'),sourceAnchor:n?{chapter:n.dataset.chapterId,page:n.dataset.sourcePage,offset:n.dataset.sourceOffset}:null,textCharacters:t?.textContent.length}});
const instrument=()=>{const audit={events:[],timers:new Map(),rafs:new Set(),observers:[],longTasks:[],digests:[],states:[]};window.__readerAudit=audit;for(const name of ['ResizeObserver','MutationObserver','IntersectionObserver']){const Native=window[name];if(!Native)continue;window[name]=class extends Native{constructor(cb){super(cb);this.auditActive=true;audit.observers.push({kind:name,ref:new WeakRef(this)})}disconnect(){this.auditActive=false;return super.disconnect()}}};for(const [set,clear,kind] of [['setTimeout','clearTimeout','timeout'],['setInterval','clearInterval','interval']]){const s=window[set],c=window[clear];window[set]=(cb,ms,...args)=>{let id=s(()=>{if(kind==='timeout')audit.timers.delete(id);cb(...args)},ms);audit.timers.set(id,kind);return id};window[clear]=id=>{audit.timers.delete(id);return c(id)}};const r=window.requestAnimationFrame,c=window.cancelAnimationFrame;window.requestAnimationFrame=cb=>{let id=r(t=>{audit.rafs.delete(id);cb(t)});audit.rafs.add(id);return id};window.cancelAnimationFrame=id=>{audit.rafs.delete(id);return c(id)};const digest=crypto.subtle.digest.bind(crypto.subtle);crypto.subtle.digest=async(...args)=>{const start=performance.now();const result=await digest(...args);audit.digests.push({at:start,duration:performance.now()-start});return result};document.fonts?.ready.then(()=>audit.fontsReady=performance.now());new PerformanceObserver(list=>{audit.longTasks.push(...list.getEntries().map(e=>({at:e.startTime,duration:e.duration})));if(audit.longTasks.length>500)audit.longTasks.splice(0,audit.longTasks.length-500)}).observe({type:'longtask',buffered:true});};
const stageInstrument=()=>{
 const stages={T0:performance.now()},caches=[];
 window.__readerStage={stages,caches,mark:key=>{if(stages[key]===undefined)stages[key]=performance.now()},registerCache:cache=>{caches.push(new WeakRef(cache));return caches.length-1}};
 let painted=false;const inspect=()=>{if(document.querySelector('.reader-opening'))window.__readerStage.mark('OPENING_START');const n=document.querySelector('[data-pagination-ready="true"]'),text=document.querySelector('[data-testid="reader-reading-text"]');if(!n||!text)return;window.__readerStage.mark('T11');if(!document.querySelector('.reader-opening')){window.__readerStage.mark('T12');if(!painted){painted=true;requestAnimationFrame(()=>requestAnimationFrame(()=>window.__readerStage.mark('T13')))}}if(n.dataset.bookMapComplete==='true')window.__readerStage.mark('T14')};
 document.addEventListener('DOMContentLoaded',()=>{new MutationObserver(inspect).observe(document.body,{subtree:true,childList:true,attributes:true});inspect()});
};
const traceRun=async(cdp,action)=>{let events=[];const listener=x=>events.push(...x.value);cdp.on('Tracing.dataCollected',listener);await cdp.send('Tracing.start',{categories:'toplevel,devtools.timeline,disabled-by-default-devtools.timeline,disabled-by-default-devtools.timeline.stack,v8,blink.user_timing',options:'record-as-much-as-possible',transferMode:'ReportEvents'});const pre=(await cdp.send('Performance.getMetrics')).metrics;try{await action()}finally{const done=new Promise(r=>cdp.once('Tracing.tracingComplete',r));await cdp.send('Tracing.end');await done;cdp.off('Tracing.dataCollected',listener)}const post=(await cdp.send('Performance.getMetrics')).metrics;const result=summarizeReaderTrace(events);for(const name of ['ScriptDuration','LayoutDuration','RecalcStyleDuration','TaskDuration'])result[name]=(post.find(x=>x.name===name)?.value||0)-(pre.find(x=>x.name===name)?.value||0);events=[];return result};
let activeContext;
try{
 const seed=await browser.newContext();const seedPage=await seed.newPage();await seedPage.goto(base+'/perf-reader.html');await seedPage.getByRole('button',{name:'Create disposable reader'}).click();await waitFn(seedPage,()=>document.querySelector('[data-testid="identity"]')?.textContent!=='anonymous');const id=await seedPage.getByTestId('identity').innerText();execFileSync(path.join(harnessRoot,'.venv-uat/bin/python'),['-c',"import sys;from pymongo import MongoClient;c=MongoClient('mongodb://127.0.0.1:27018/earnalism_uat?replicaSet=earnalism-uat-rs0');r=c.earnalism_uat.users.update_one({'id':sys.argv[1]},{'$set':{'reading_seconds_balance':20000,'wallet_seconds':20000}});assert r.matched_count==1;c.close()",id],{stdio:'pipe'});await seedPage.evaluate(()=>localStorage.setItem('earnalism_reading_pass_device_v1',crypto.randomUUID()));const storage=await seed.storageState();await seed.close();
 const preview=await browser.newContext();const guest=await preview.newPage();const previewRequests=[];guest.on('request',r=>{const m=new URL(r.url()).pathname.match(/\/pages\/(\d+)$/);if(m)previewRequests.push(Number(m[1]))});await guest.goto(base+'/reader/dracula?p=1');await ready(guest);const deny=await preview.request.get(base+'/api/reading-pass/books/dracula/pages/4');evidence.preview={requested_pages:previewRequests,unauthorized_chunk_requests:previewRequests.filter(n=>n>3).length,protected_status:deny.status(),...await sample(guest)};await preview.close();if(deny.status()!==401||evidence.preview.unauthorized_chunk_requests)throw Error('Preview security failure');
 for(const [width,height] of [[1440,900],[390,844],[844,390]]){
  let context,page,cdp,requests=[];
  const attach=async()=>{context=await browser.newContext({viewport:{width,height},storageState:storage});activeContext=context;await context.addInitScript(instrument);await context.addInitScript(stageInstrument);page=await context.newPage();cdp=await context.newCDPSession(page);await cdp.send('Performance.enable');requests=[];const ids=new WeakMap();page.on('pageerror',e=>evidence.errors.push(e.message));page.on('request',r=>{if(!new URL(r.url()).pathname.startsWith('/api/'))return;ids.set(r,requests.length);requests.push({path:new URL(r.url()).pathname,method:r.method(),at:Date.now(),lease_present:!!r.headers()['x-reading-pass-lease']})});page.on('response',r=>{const row=requests[ids.get(r.request())];if(row){row.status=r.status();row.responseAt=Date.now();row.cacheControl=r.headers()['cache-control']}});page.on('requestfinished',r=>{const row=requests[ids.get(r)];if(row){row.completedAt=Date.now();r.sizes().then(s=>row.bytes=s.responseBodySize).catch(()=>{})}});return page};
  for(const kind of ['cold','warm'])for(let iteration=0;iteration<(kind==='cold'?10:20);iteration++){
   await new Promise(r=>setTimeout(r,5500));if(kind==='cold'||iteration===0)await attach();const before=requests.length;const start=performance.now();let cpu=await traceRun(cdp,async()=>{await page.goto(base+'/reader/dracula?p=4');await ready(page);await waitFn(page,()=>window.__readerStage.stages.T13!==undefined);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))))});const elapsed=performance.now()-start;const value=await sample(page);const stages=await page.evaluate(()=>({...window.__readerStage.stages}));const row={width,height,kind,iteration,driverObservedMs:elapsed,firstReadableMs:stages.T13-stages.T0,contentReadyMs:stages.T11-stages.T0,stages,...value,cpu,requests:requests.slice(before)};evidence.loads.push(row);if(value.overflow||row.requests.some(x=>x.status>=400))throw Error('Overflow or API failure');console.error(kind+' '+width+' '+iteration+' '+row.firstReadableMs.toFixed(1)+'ms pagination='+value.dataset.paginationMs);fs.writeFileSync(evidenceOutput,JSON.stringify(evidence,null,2));
   if(kind==='cold'){await route(page,'/perf-reader.html');await page.getByTestId('identity').waitFor();await page.waitForTimeout(300);await context.close();activeContext=null}else if(iteration!==19){await route(page,'/perf-reader.html');await page.getByTestId('identity').waitFor();await page.waitForTimeout(100)}
  }
  const times=[];for(let i=0;i<40;i++){await page.waitForTimeout(1500);const old=(await sample(page)).dataset.visualPageIndex;const start=performance.now();await page.getByRole('button',{name:i%2?'Previous page':'Next page',exact:true}).click();await waitFn(page,old=>document.querySelector('.reader-v2__visual-viewport')?.dataset.visualPageIndex!==old&&document.querySelector('.reader-v2__visual-viewport')?.dataset.paginationReady==='true',old);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));times.push(performance.now()-start);await waitFn(page,()=>[...document.querySelectorAll('.reader-v2__page-content')].every(n=>n.getAnimations().every(a=>a.playState!=='running')))}evidence.turns.push({width,height,...stats(times),values:times,transitionMs:280});
  if(width===1440){evidence.layoutPhases=[];for(const [name,action] of [['desktop-to-portrait',()=>page.setViewportSize({width:390,height:844})],['portrait-to-landscape',()=>page.setViewportSize({width:844,height:390})],['text-size-change',()=>page.getByRole('button',{name:'Increase text size',exact:true}).first().click()]]){const before=await sample(page);let wall=performance.now();const cpu=await traceRun(cdp,async()=>{await action();await page.waitForTimeout(150);await page.locator('[data-pagination-ready="true"]').waitFor();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))))});evidence.layoutPhases.push({phase:name,cpu,observedMs:performance.now()-wall,before,...await sample(page)})}}
  await route(page,'/perf-reader.html');await page.getByTestId('identity').waitFor();await page.waitForTimeout(500);await context.close();activeContext=null;fs.writeFileSync(evidenceOutput,JSON.stringify(evidence,null,2));
 }
 evidence.distributions=[];for(const width of [1440,390,844])for(const kind of ['cold','warm']){const rows=evidence.loads.filter(x=>x.width===width&&x.kind===kind);evidence.distributions.push({width,kind,firstReadable:stats(rows.map(x=>x.firstReadableMs)),contentReady:stats(rows.map(x=>x.contentReadyMs))})}
 evidence.fullAppStartup='NOT_MEASURED';
}catch(e){evidence.failure=e.message;process.exitCode=1;console.error('FAILED '+e.message)}finally{if(activeContext)await activeContext.close();await browser.close();await new Promise(r=>proxy.close(r));fs.writeFileSync(evidenceOutput,JSON.stringify(evidence,null,2));fs.rmSync(output,{recursive:true,force:true});fs.rmSync(temp,{recursive:true,force:true});}
