#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from mutagen.mp3 import MP3


ROOT = Path(__file__).resolve().parents[1]
RESTORATION_MANIFEST = ROOT / "internal" / "audiobook_lab" / "generated_candidate_restoration" / "restoration_manifest_20260702.json"
COVER_MAP = ROOT / "internal" / "audiobook_lab" / "release_gate" / "cover_cloudinary_url_mapping.json"
OUTPUT_JSON = ROOT / "internal" / "audiobook_lab" / "release_gate" / "go_live_readiness_ranking.json"
OUTPUT_MD = ROOT / "internal" / "audiobook_lab" / "release_gate" / "go_live_readiness_ranking.md"
SUSPICIOUS_TEXT_RE = re.compile(r"\bTraceback\b|\bException\b|\bJSONDecodeError\b|Generated by ", re.IGNORECASE)


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S%z")


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_text(path: Path, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(value, encoding="utf-8")


def unique_candidates() -> list[dict[str, Any]]:
    payload = read_json(RESTORATION_MANIFEST)
    seen: set[str] = set()
    rows: list[dict[str, Any]] = []
    for item in payload.get("candidates") or []:
        if not isinstance(item, dict):
            continue
        slug = str(item.get("slug") or "").strip()
        if not slug or slug in seen:
            continue
        seen.add(slug)
        rows.append(item)
    return rows


def mp3_duration_ms(path: Path) -> int:
    return int(MP3(path).info.length * 1000)


def highlight_total_ms(path: Path) -> int:
    payload = read_json(path)
    chapters = payload.get("chapters") or []
    if not isinstance(chapters, list):
        return 0
    return int(sum(int(item.get("duration_ms") or 0) for item in chapters if isinstance(item, dict)))


def compute_row(candidate: dict[str, Any], cover_lookup: dict[str, dict[str, Any]]) -> dict[str, Any]:
    slug = str(candidate.get("slug") or "").strip()
    content_root = ROOT / "content" / "books" / slug
    controlled_root = ROOT / "data" / "controlled_publications" / slug
    release_root = ROOT / "internal" / "audiobook_lab" / "release_gate" / "sync_manifests" / slug
    enhanced_mp3 = ROOT / "internal" / "audiobook_lab" / "enhanced_candidates" / slug / f"{slug}_enhanced.mp3"

    book_json = content_root / "book.json"
    rights_path = content_root / "source-rights.md"
    reader_manifest = controlled_root / "reader_manifest.json"
    highlight_sync = controlled_root / "highlight_sync.json"
    public_book = controlled_root / "public_book.json"
    source_evidence = controlled_root / "source_evidence.json"
    approval_evidence = controlled_root / "approval_evidence.json"
    checksum_manifest = controlled_root / "checksum_manifest.json"
    enhanced_sync = release_root / f"{slug}_enhanced.json"
    fallback_sync = release_root / f"{slug}_fallback.json"
    content_chapter_dir = content_root / "chapters"
    controlled_chapter_dir = controlled_root / "chapters"
    raw_source = content_root / "raw" / "source.txt"

    rights_text = rights_path.read_text(encoding="utf-8") if rights_path.exists() else ""
    rights_ready = "ready_for_auto_publication" in rights_text.lower()

    alignment_delta_ms: int | None = None
    alignment_ok = False
    if enhanced_mp3.exists() and highlight_sync.exists():
        try:
            alignment_delta_ms = mp3_duration_ms(enhanced_mp3) - highlight_total_ms(highlight_sync)
            alignment_ok = abs(alignment_delta_ms) <= 1000
        except Exception:
            alignment_delta_ms = None

    cover_item = cover_lookup.get(slug, {})
    cover_ready = bool(cover_item.get("front_assigned") and cover_item.get("back_assigned"))
    release_pack_ready = public_book.exists() and source_evidence.exists() and approval_evidence.exists() and checksum_manifest.exists()
    suspicious_hits: list[str] = []
    chapter_count_match = True
    chapter_files = sorted(content_chapter_dir.glob("*.json"))
    if not chapter_files:
        chapter_files = sorted(controlled_chapter_dir.glob("chapter-*.json"))
    if reader_manifest.exists():
        try:
            manifest_payload = read_json(reader_manifest)
            expected_count = len(manifest_payload.get("chapters") or [])
            actual_count = len(chapter_files)
            chapter_count_match = expected_count == actual_count and expected_count > 0
            if not chapter_count_match:
                suspicious_hits.append(f"chapter_count_mismatch:{actual_count}!={expected_count}")
        except Exception:
            chapter_count_match = False
            suspicious_hits.append("reader_manifest_unreadable")
    else:
        chapter_count_match = False

    for chapter_path in chapter_files:
        try:
            chapter_payload = read_json(chapter_path)
            text = json.dumps(chapter_payload, ensure_ascii=False)
        except Exception:
            suspicious_hits.append(f"unreadable:{chapter_path.name}")
            continue
        if SUSPICIOUS_TEXT_RE.search(text):
            suspicious_hits.append(f"suspicious:{chapter_path.name}")
            break

    if raw_source.exists():
        try:
            raw_text = raw_source.read_text(encoding="utf-8", errors="replace")
            if SUSPICIOUS_TEXT_RE.search(raw_text):
                suspicious_hits.append("suspicious:raw/source.txt")
        except Exception:
            suspicious_hits.append("unreadable:raw/source.txt")

    sanitized_content_ready = (
        book_json.exists()
        and rights_path.exists()
        and reader_manifest.exists()
        and highlight_sync.exists()
        and chapter_count_match
        and not suspicious_hits
    )
    premium_audio_ready = enhanced_mp3.exists()
    sync_ready = premium_audio_ready and highlight_sync.exists() and alignment_ok

    score = 0.0
    score += 2.0 if sanitized_content_ready else 0.0
    score += 2.0 if premium_audio_ready else 0.0
    score += 2.0 if sync_ready else 0.0
    score += 1.0 if cover_ready else 0.0
    score += 1.0 if public_book.exists() else 0.0
    score += 1.0 if release_pack_ready else 0.0
    score += 1.0 if rights_ready else 0.0

    blockers: list[str] = []
    if not sanitized_content_ready:
        blockers.append("sanitized_content_or_reader_artifacts_missing")
    if not premium_audio_ready:
        blockers.append("premium_audio_missing")
    if not sync_ready:
        blockers.append("premium_sync_missing_or_misaligned")
    if not cover_ready:
        blockers.append("cover_assignment_missing")
    if not public_book.exists():
        blockers.append("public_book_missing")
    if not release_pack_ready:
        blockers.append("release_artifact_pack_incomplete")
    if not rights_ready:
        blockers.append("rights_note_not_marked_ready_for_auto_publication")

    next_action = "READY_FOR_FINAL_HUMAN_GO_LIVE_REVIEW"
    if blockers:
        if "sanitized_content_or_reader_artifacts_missing" in blockers:
            next_action = "REPAIR_SANITIZED_CONTENT_AND_READER_ARTIFACTS"
        elif "premium_audio_missing" in blockers:
            next_action = "GENERATE_PREMIUM_AUDIO"
        elif "premium_sync_missing_or_misaligned" in blockers:
            next_action = "BACKFILL_OR_REPAIR_PREMIUM_SYNC"
        elif "cover_assignment_missing" in blockers:
            next_action = "ASSIGN_FRONT_AND_BACK_COVERS"
        elif "public_book_missing" in blockers or "release_artifact_pack_incomplete" in blockers:
            next_action = "BACKFILL_CONTROLLED_PUBLICATION_ARTIFACTS"
        elif "rights_note_not_marked_ready_for_auto_publication" in blockers:
            next_action = "COMPLETE_RIGHTS_EVIDENCE_AND_SIGNOFF"

    return {
        "slug": slug,
        "title": candidate.get("title") or slug,
        "language": candidate.get("language") or "",
        "readiness_score_10": round(score, 1),
        "sanitized_content_ready": sanitized_content_ready,
        "premium_audio_ready": premium_audio_ready,
        "sync_ready": sync_ready,
        "cover_ready": cover_ready,
        "public_book_ready": public_book.exists(),
        "release_pack_ready": release_pack_ready,
        "rights_ready": rights_ready,
        "alignment_delta_ms": alignment_delta_ms,
        "sanitation_hits": suspicious_hits,
        "has_enhanced_sync_manifest": enhanced_sync.exists(),
        "has_fallback_sync_manifest": fallback_sync.exists(),
        "next_action": next_action,
        "blockers": blockers,
    }


def markdown_report(rows: list[dict[str, Any]]) -> str:
    distribution = Counter(row["readiness_score_10"] for row in rows)
    lines = [
        "# GO LIVE Readiness Ranking",
        "",
        f"- generated_at: {now_iso()}",
        f"- total_titles: {len(rows)}",
        f"- score_10_count: {distribution.get(10.0, 0)}",
        f"- score_9_5_count: {distribution.get(9.5, 0)}",
        f"- score_8_plus_count: {sum(1 for row in rows if row['readiness_score_10'] >= 8.0)}",
        f"- premium_audio_ready_count: {sum(1 for row in rows if row['premium_audio_ready'])}",
        f"- sync_ready_count: {sum(1 for row in rows if row['sync_ready'])}",
        f"- cover_ready_count: {sum(1 for row in rows if row['cover_ready'])}",
        f"- rights_ready_count: {sum(1 for row in rows if row['rights_ready'])}",
        "",
        "## Top 25",
        "",
        "| Rank | Slug | Score | Lang | Next action | Blockers |",
        "| ---: | --- | ---: | --- | --- | --- |",
    ]
    for index, row in enumerate(rows[:25], start=1):
        blockers = ", ".join(row["blockers"]) if row["blockers"] else "none"
        lines.append(
            f"| {index} | {row['slug']} | {row['readiness_score_10']} | {row['language']} | {row['next_action']} | {blockers} |"
        )

    lines.extend(["", "## Score Distribution", ""])
    for score, count in sorted(distribution.items(), reverse=True):
        lines.append(f"- {score}: {count}")

    lines.extend(["", "## Highest-Leverage Blockers", ""])
    blocker_counts: Counter[str] = Counter()
    for row in rows:
        blocker_counts.update(row["blockers"])
    for blocker, count in blocker_counts.most_common():
        lines.append(f"- {blocker}: {count}")

    return "\n".join(lines) + "\n"


def main() -> int:
    cover_payload = read_json(COVER_MAP)
    cover_lookup = {
        item["slug"]: item
        for item in (cover_payload.get("items") or [])
        if isinstance(item, dict) and item.get("slug")
    }
    rows = [compute_row(candidate, cover_lookup) for candidate in unique_candidates()]
    rows.sort(key=lambda item: (-item["readiness_score_10"], item["slug"]))
    payload = {
        "generated_at": now_iso(),
        "total_titles": len(rows),
        "rows": rows,
    }
    write_json(OUTPUT_JSON, payload)
    write_text(OUTPUT_MD, markdown_report(rows))
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
