#!/usr/bin/env node
import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";

const root = process.cwd(); const validator = path.join(root, "scripts/validate_seamless_brand_final_evidence_inputs.py"); const temp = fs.mkdtempSync(path.join(os.tmpdir(), "pr344-final-inputs-"));
const sha = (file) => crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex"); const head = execFileSync("git", ["rev-parse", "HEAD"], { encoding: "utf8" }).trim();
const production = (() => { const files=[]; const walk=d=>fs.readdirSync(d,{withFileTypes:true}).forEach(e=>{const f=path.join(d,e.name);if(e.isDirectory())walk(f);else if(!f.includes("__tests__")&&!/\.(test|spec)\./.test(f))files.push(f)});walk(path.join(root,"frontend/src"));walk(path.join(root,"frontend/public"));files.push(...["frontend/package.json","frontend/package-lock.json","frontend/vercel.json"].map(f=>path.join(root,f)));return crypto.createHash("sha256").update(files.sort().map(f=>`${sha(f)}  ${path.relative(root,f)}\n`).join("")).digest("hex")})();
const write=(file,value)=>fs.writeFileSync(file,typeof value === "string" ? value : JSON.stringify(value)); const run=()=>execFileSync("python3",[validator,"--inputs",path.join(temp,"final-evidence-inputs.json")],{cwd:root,stdio:"pipe"});
const reference=(name,value={})=>{const file=path.join(temp,`${name}.json`);write(file,{ok:true,...value});return {path:file,sha256:sha(file)}};
const make=()=>{const chromium=reference("chromium");const firefox=reference("firefox");const webkit=reference("webkit");const staticResult=reference("static");const hashes=reference("hashes");const carry=reference("carry");const input={current_pr_head:head,production_surface_sha256:production,canonical_logo_sha256:sha(path.join(root,"frontend/public/assets/brand/earnalism-brand-lockup.png")),chromium:{summary_path:chromium.path,summary_sha256:chromium.sha256,expected:65,captured:65,stable:65},firefox:{summary_path:firefox.path,summary_sha256:firefox.sha256,expected:20,captured:20,stable:20,result:"PASS"},webkit:{summary_path:webkit.path,summary_sha256:webkit.sha256,expected:20,captured:20,stable:20,result:"PASS"},static_snapshot:{path:staticResult.path,sha256:staticResult.sha256,expected:1,inspected:1,passing:1,result:"PASS"},route_hashes:{path:hashes.path,sha256:hashes.sha256,result:"PASS"},approval_carry_forward:{path:carry.path,sha256:carry.sha256,result:"PASS"},reader_safety_result:"PASS",listener_safety_result:"PASS",interaction_result:"PASS",zoom_result:"PASS",error_status_result:"PASS",rendered_ui_defect_count:0,production_mutation_count:0};write(path.join(temp,"final-evidence-inputs.json"),input);return input};
let cases=0;const test=(name,fn)=>{fn();cases+=1;console.log(`PASS ${cases}: ${name}`)};const invalid=mutate=>{const input=make();mutate(input);write(path.join(temp,"final-evidence-inputs.json"),input);assert.throws(run)};
test("valid exact-head input set passes",()=>{make();run()});
test("wrong head fails",()=>invalid(x=>x.current_pr_head="wrong")); test("wrong production hash fails",()=>invalid(x=>x.production_surface_sha256="wrong")); test("wrong logo hash fails",()=>invalid(x=>x.canonical_logo_sha256="wrong")); test("missing Chromium state fails",()=>invalid(x=>x.chromium.captured=64)); test("unstable Chromium state fails",()=>invalid(x=>x.chromium.stable=64)); test("Library focus failure fails",()=>invalid(x=>x.interaction_result="FAIL")); test("Reader safety failure fails",()=>invalid(x=>x.reader_safety_result="FAIL")); test("Listener safety failure fails",()=>invalid(x=>x.listener_safety_result="FAIL")); test("static snapshot failure fails",()=>invalid(x=>x.static_snapshot.result="FAIL")); test("unexpected route-family hash change fails",()=>invalid(x=>x.route_hashes.result="FAIL")); test("Firefox failure fails",()=>invalid(x=>x.firefox.result="FAIL")); test("WebKit failure fails",()=>invalid(x=>x.webkit.result="FAIL")); test("missing referenced file fails",()=>invalid(x=>x.webkit.summary_path=path.join(temp,"missing.json"))); test("SHA mismatch fails",()=>invalid(x=>x.firefox.summary_sha256="wrong")); test("production mutation fails",()=>invalid(x=>x.production_mutation_count=1)); test("PENDING value fails",()=>invalid(x=>x.interaction_result="PENDING"));
console.log(JSON.stringify({result:"PASS",testCaseCount:cases}));
