#!/usr/bin/env node
import fs from "node:fs"; import path from "node:path";
const script=fs.readFileSync(new URL("./capture_book_commerce_final_review.mjs",import.meta.url),"utf8");
const required=["book-about-desktop-1440","book-chapters-desktop","book-chapters-mobile","book-secondary-desktop","commerce-1024","commerce-768","commerce-430","commerce-320","book-interaction-results.json","commerce-geometry-results.json","ArrowLeft","Details","serviceWorkers:\"block\"","probeFonts","webkit-network-diagnostics.json","browser-font-results.json","capture-stability-results.json","pricing-pack-30m","NOT_APPLICABLE_HISTORICAL_SOURCE","BOOK_COMMERCE_FORCE_CAPTURE_FAILURE"];
const absent=required.filter((id)=>!script.includes(id)); if(absent.length) throw new Error(`Required harness evidence absent: ${absent.join(", ")}`);
const workflow=fs.readFileSync(new URL("../.github/workflows/book-commerce-final-review.yml",import.meta.url),"utf8");
if(!/BOOK_COMMERCE_CAPTURE_MODE=historical-v1/.test(workflow) || !/BOOK_COMMERCE_CAPTURE_MODE=current-candidate/.test(workflow) || !/cp scripts\/lib\/book_commerce_capture_contract\.mjs "\$base_dir\/scripts\/lib\/"/.test(workflow) || !/cp -R "\$base_dir\/uat\/evidence\/book-commerce-final-review\/before\/\."/.test(workflow) || !/exit "\$capture_status"/.test(workflow)) throw new Error("Workflow must materialize the historical adapter, select explicit modes, and retain failed baseline diagnostics");
const out=process.env.BOOK_COMMERCE_TEST_OUTPUT; if(out){ for(const file of ["capture-results.json","all-browser-capture-results.json","book-interaction-results.json","fixture-offer-results.json","commerce-geometry-results.json","heading-results.json","book-content-capability-results.json","live-offer-results.json","book-commerce-browser-results.json","browser-font-results.json","capture-stability-results.json","webkit-network-diagnostics.json"]){if(!fs.existsSync(path.join(out,file)))throw new Error(`Required result missing: ${file}`); const body=fs.readFileSync(path.join(out,file),"utf8"); if(/PENDING|NOT RUN|WORKFLOW RUNNING/.test(body))throw new Error(`Non-final evidence in ${file}`);} }
console.log(JSON.stringify({status:"PASS",required_states:required.length}));
