import pathlib,json,re,hashlib,datetime
B=pathlib.Path('/workspace/scratch/181ef0a25f05');R=pathlib.Path('/tmp/earnalism-main-approved-integration');h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();load=lambda p:json.loads(p.read_text());t=B/'bengali-order-only-20261003-v2/lokrahasya';c=t/'proposal/data/controlled_publications/lokrahasya';pre=t/'archive-prior-proposal';v=load(t/'validation.json');proofpath=R/'internal/legal/catalogue_clearance_20261002/bengali/lokrahasya-multichapter-source-comparison.json';proof=load(proofpath);leafs={x['title']:x for x in proof['source_chapters']};maps={x['id']:int(re.search(r'from\s*=\s*["\']?(\d+)',leafs[x['matched_source']]['wikitext']).group(1))for x in proof['comparisons']};tit={x['id']:x['matched_source']for x in proof['comparisons']};reader=load(c/'reader_manifest.json');xs=reader['chapters'];ids=[x['id']for x in xs];assert ids==v['source_order_ids'];assert [maps[x]for x in ids]==sorted(maps.values());assert len(ids)==len(set(ids))==16;bodies=[];preserved=[]
for x in xs:
 q=c/'chapters'/(x['id']+'.json');old=load(pre/'chapters'/q.name);new=load(q);assert new['content']==old['content'];assert new['content_hash']==old['content_hash'];assert new['sourceSha256']==old['sourceSha256'];assert new['title']==tit[x['id']].split('/')[-1];assert new['order']==x['order'];assert all(new[k]==val for k,val in old.items()if k not in ['title','order','updated_at']);bodies.append(new['content']);preserved.append({'id':new['id'],'source_first_page':maps[new['id']],'body_sha256':new['content_hash'],'current_order':new['order'],'source_title':new['title']})
agg=hashlib.sha256('\n\n'.join(bodies).encode()).hexdigest();assert agg==v['new_content_hash'];assert load(c/'public_book.json')['content_hash']==agg;assert load(c/'source_evidence.json')['content_hash']==agg;assert load(c/'publication_authorization.json')['content_sha256']==agg;assert load(c/'cover_provenance.json')['edition_binding']['content_sha256']==agg
for n in ['public_book.json','publication_manifest.json']:
 doc=load(c/n);z=doc['chapters']if n=='public_book.json'else doc['content']['chapters'];assert [x['id']for x in z]==ids;assert [x['order']for x in z]==list(range(1,17))
oldlicense=load(pre/'license_notice.json');newlicense=load(c/'license_notice.json');assert all(newlicense[k]==v for k,v in oldlicense.items()if k!='chapter_sha256');assert newlicense['chapter_sha256']==[x['body_sha256']for x in preserved]
for n in ['highlight_sync.json']+[str(p.relative_to(c))for p in(c/'covers').glob('*')]:assert (c/n).read_bytes()==(pre/n).read_bytes()
for x in load(c/'checksum_manifest.json')['files']:assert h(c/x['file'])==x['sha256']
d=load(c/'rights_decision.json');assert d['status']=='PROPOSED'and not d['conditions_satisfied'];assert d['territories']==['IN']
for k,sha in d['components'].items():assert h(c/(k+'.json'))==sha
man=load(c/'publication_manifest.json');
for k,sha in man['artifacts'].items():assert h(c/(k+'.json'))==sha
old=load(pre/'source_evidence.json');new=load(c/'source_evidence.json');assert new['source_hash']==old['source_hash']==v['source_hash_unchanged'];assert load(c/'public_book.json')['rights_basis']==load(pre/'public_book.json')['rights_basis'];assert h(c/'rights_decision.json')==v['decision_raw_sha256']
receipt={'reviewer':'Independent Codex reviewer B','reviewed_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'slug':'lokrahasya','disposition':'PASS_ONE_ORDER_ONLY_METADATA_REMEDIATION_UNACCEPTED_PROPOSAL','exact_package':str(c),'version':v['package_version'],'metadata_source_order':preserved,'source_order_basis':{'path':str(proofpath),'sha256':h(proofpath),'method':'Independently map exact pinned matched-source transclusion pages and sort physical first scan pages; all16 source-backed IDs and titles represented once.'},'previous_order_aggregate':v['old_content_hash'],'new_order_aggregate':agg,'source_sha256_unchanged':v['source_hash_unchanged'],'old_proposal_exact_archive':str(pre),'old_body_art_sync_and_rights_facts_preserved':True,'license_terms_preserved_with_chapter_hash_sequence_rebound':True,'chapter_metadata_changes_only':['order','title_exact_source_leaf_basename','actual_updated_at'],'checksum_and_component_and_manifest_bindings':'PASS','decision_raw_sha256':h(c/'rights_decision.json'),'owner_provenance_gate_review_reused':'bfe33ca2a412310658540a44ac6c7d23b9b1b58aa54255f03cccda51223bf8ac','actual_acceptance_by_B':False,'canonical_mutations':False,'source_body_visual_reviews_repeated':False,'downloads_renders_paid_generation':0,'production_observed':False,'next_gate':'Root actual prospective acceptance rebinding followed by two independent exact accepted-package/tree reviews and protected normal release checks.'}
p=B/'new-acceptance-review-b-20261003/lokrahasya-order-only-delta-review-b.json';p.write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print(h(p),agg,[(x['id'],x['source_first_page'])for x in preserved])
