export const LOCAL_LIBRARY_FALLBACK_BOOKS = [
  {
    slug: "devdas",
    title: "দেবদাস / Devdas",
    author: "Sarat Chandra Chattopadhyay",
    short_description: "A clean Earnalism reader edition of দেবদাস / Devdas, prepared from a legally cleared public-domain Bengali source with source boilerplate removed.",
    publication_status: "LIVE_APPROVED",
    reader_enabled: true,
    preview_enabled: true,
    preview_url: "/reader/devdas",
    chapters: [{ id: "devdas-canonical-page-1", is_preview: true }],
    audiobook_enabled: false,
    estimated_reading_time: "105 min",
    category_slug: "bengali-classics",
  },
  {
    slug: "pather-panchali",
    title: "পথের পাঁচালী / Pather Panchali",
    author: "Bibhutibhushan Bandyopadhyay",
    short_description: "A clean Earnalism reader edition of পথের পাঁচালী / Pather Panchali, prepared from a legally cleared public-domain Bengali source with source boilerplate removed.",
    publication_status: "LIVE_APPROVED",
    reader_enabled: true,
    preview_enabled: true,
    preview_url: "/reader/pather-panchali",
    chapters: [{ id: "pather-panchali-canonical-page-1", is_preview: true }],
    audiobook_enabled: false,
    estimated_reading_time: "87 min",
    category_slug: "bengali-classics",
  },
  {
    slug: "hungry-stones",
    title: "Kshudhita Pashan / The Hungry Stones",
    author: "Rabindranath Tagore",
    short_description: "A clean Earnalism reader edition of Kshudhita Pashan / The Hungry Stones, prepared from a legally cleared public-domain classic source with source boilerplate removed.",
    publication_status: "LIVE_APPROVED",
    reader_enabled: true,
    preview_enabled: true,
    preview_url: "/reader/hungry-stones",
    chapters: [{ id: "hungry-stones-canonical-page-1", is_preview: true }],
    audiobook_enabled: false,
    estimated_reading_time: "20 min",
    category_slug: "bengali-classics",
  },
];
